//! The three starter templates (REQ-033, slice 4).
//!
//! This is where a [`ScaffoldRequest`] becomes a list of files. It is a separate module from
//! [`crate::scaffold`] because the *rules* are the part worth testing hard and they are
//! independent of what the templates happen to contain: a change to a README's wording must
//! not be able to break the manifest validator's tests, and a change to the validator must not
//! require re-reading three templates to find out what changed.
//!
//! # The one rule about content
//!
//! **No template contains anything that looks like a credential.** Not a token, not a key, not
//! a half-filled `.env` with a plausible-looking value. The reason is the request's own risk
//! note — scaffolds get copied into public repositories — and the failure mode is specific: a
//! starter that ships `API_TOKEN=sk_live_4eC39Hq...` teaches the reader that a value which
//! looks like that belongs in a file that gets committed. The example environment file ships
//! with its keys present and their values empty, which is what makes the README's warning
//! concrete rather than a platitude.
//!
//! The second half of that rule is enforced by a test, not by review: [`tests::no_template_looks_like_it_carries_a_credential`]
//! reads every generated byte and refuses patterns that would be found by a secret scanner.
//! Review catches what you are looking at; the test catches what you added afterwards.

use crate::Result;
use crate::scaffold::{
    Scaffold, ScaffoldFile, ScaffoldKind, ScaffoldRequest, ScaffoldTarget, validate_scaffold,
};

/// Generate the starter archive for one request.
///
/// `validate_scaffold` runs here rather than only in the API handler, so a future caller that
/// reaches the generator from somewhere else gets the same refusal instead of a directory name
/// nobody validated.
pub fn generate(kind: ScaffoldKind, name: &str, target: ScaffoldTarget) -> Result<Scaffold> {
    let request = ScaffoldRequest {
        kind,
        name: name.to_string(),
        target,
    };
    validate_scaffold(&request)?;

    let files = match kind {
        ScaffoldKind::Plugin => plugin(&name, target),
        ScaffoldKind::Theme => theme(&name, target),
        ScaffoldKind::Workflow => workflow(&name, target),
    };

    let byte_size = files.iter().map(ScaffoldFile::byte_size).sum();
    Ok(Scaffold {
        kind,
        name: name.to_string(),
        target,
        files,
        byte_size,
    })
}

/// The manifest every template ships, as a JSON string built from values rather than a constant.
///
/// Building it means the name in the manifest cannot disagree with the name of the directory,
/// and the `kind` cannot disagree with the tab it was generated from — those two are the
/// fields [`crate::scaffold::validate_manifest`] checks first, and a mismatch between the two
/// is an extension that passes review and fails to boot.
fn manifest(kind: ScaffoldKind, name: &str, entry: &str, display_name: &str) -> String {
    // Every value interpolated here is either a literal from this module or a name that has
    // been slug-validated to letters, digits, `-` and `_`. None can contain a quote or a
    // backslash, so the interpolation cannot produce invalid JSON. That reasoning is why the
    // validator *refuses* a bad character rather than escaping it: an escaping path would need
    // its own tests, and a test that only passes because nothing can reach it is not a test.
    format!(
        "{{\n  \"kind\": \"{kind}\",\n  \"version\": \"1.0.0\",\n  \"name\": \"{name}\",\n  \
         \"entry\": \"{entry}\",\n  \"displayName\": \"{display_name}\",\n  \
         \"description\": \"A {kind} extension.\"\n}}\n",
        kind = kind.as_str(),
    )
}

/// `.gitignore` — every template ships one.
fn gitignore() -> ScaffoldFile {
    ScaffoldFile::hidden(
        ".gitignore",
        "# Build output and dependencies\nnode_modules/\ndist/\n\n\
         # Local configuration. The example file is committed; the real one is not.\n\
         .env\n.env.local\n\n\
         # Editor noise\n.DS_Store\n*.log\n",
    )
}

/// The example environment file: keys present, values empty.
///
/// Empty on purpose — see the module doc. A commented placeholder is the difference between
/// "here is where your token goes" and "here is a token".
fn env_example() -> ScaffoldFile {
    ScaffoldFile::hidden(
        ".env.example",
        "# Copy this file to .env and fill it in. Never commit the copy.\n\
         #\n\
         # The value below is intentionally empty. A starter that shipped a working-looking\n\
         # token here would teach you to paste the real one next to it.\n\
         OMNION_BASE_URL=\nOMNION_TOKEN=\n",
    )
}

/// The shared README warning, worded the way the risk note asks for.
fn readme(name: &str, kind: ScaffoldKind, body: &str) -> ScaffoldFile {
    ScaffoldFile::new(
        "README.md",
        format!(
            "# {name}\n\n\
             A {kind} starter generated by Omnion.\n\n\
             {body}\n\n\
             ## Do not commit credentials\n\n\
             This project talks to Omnion with a token, and a token in a public repository is a\n\
             credential anybody can use. `.gitignore` already excludes `.env`; leave it that way.\n\
             If a token is ever committed, rotate it in the panel — deleting the commit does not\n\
             take it back.\n\n\
             ## Before you publish\n\n\
             Run `omnion manifest validate` against `omnion.manifest.json`. The panel validates\n\
             with the same code the platform's loader uses, so a manifest that passes there is a\n\
             manifest the platform will attempt to load.\n",
            kind = kind.label().to_lowercase(),
        ),
    )
}

// ───────────────────────────────────────────────────────────────── plugin

fn plugin(name: &str, target: ScaffoldTarget) -> Vec<ScaffoldFile> {
    // The target is recorded on the generation row and deliberately does not change a byte of
    // the generated tree -- see `ScaffoldTarget`'s doc. Reading it here keeps the parameter
    // honest for a future per-target template without pretending one exists today.
    let _aimed_at = target;
    let title = title_case(name);
    vec![
        ScaffoldFile::new(
            "omnion.manifest.json",
            manifest(ScaffoldKind::Plugin, name, "dist/index.js", &title),
        ),
        ScaffoldFile::new(
            "src/index.ts",
            format!(
                "// {title}\n\
                 //\n\
                 // A plugin's entry point. The platform calls `activate` once, with the\n\
                 // services it is willing to hand an extension; everything else is yours.\n\
                 import type {{ PluginContext }} from \"@omnion/sdk\";\n\n\
                 export function activate(context: PluginContext) {{\n\
                 \x20 context.log.info(\"{name} activated\");\n\n\
                 \x20 // Register whatever your extension contributes. The two calls below are the\n\
                 \x20 // whole surface for a first run — delete them and add your own.\n\
                 \x20 context.routes.register({{ path: \"/{name}\", handler: hello }});\n\
                 \x20 context.admin.addPanel({{\n\
                 \x20   title: \"{title}\",\n\
                 \x20   render: () => \"<p>Hello from {name}.</p>\",\n\
                 \x20 }});\n\
                 }}\n\n\
                 function hello() {{\n\
                 \x20 return {{ status: 200, body: {{ plugin: \"{name}\" }} }};\n\
                 }}\n",
                title = title,
            ),
        ),
        ScaffoldFile::new(
            "package.json",
            format!(
                "{{\n  \"name\": \"{name}\",\n  \"version\": \"1.0.0\",\n  \"private\": true,\n  \
                 \"type\": \"module\",\n  \"scripts\": {{\n    \"build\": \"tsc -p tsconfig.json\",\n    \
                 \"check\": \"tsc -p tsconfig.json --noEmit\"\n  }},\n  \
                 \"devDependencies\": {{\n    \"@omnion/sdk\": \"^1.0.0\",\n    \
                 \"typescript\": \"^5.0.0\"\n  }}\n}}\n"
            ),
        ),
        ScaffoldFile::new(
            "tsconfig.json",
            "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"ES2022\",\n    \
             \"moduleResolution\": \"bundler\",\n    \"strict\": true,\n    \"outDir\": \"dist\",\n    \
             \"declaration\": true\n  },\n  \"include\": [\"src\"]\n}\n",
        ),
        ScaffoldFile::new(
            "src/types.ts",
            "export interface PluginRecord {\n  id: string;\n  createdAt: string;\n}\n",
        ),
        ScaffoldFile::new(
            ".env.example",
            "# A plugin usually talks to Omnion only through the host, so this file is\n\
             # usually empty. Uncomment if you add an external call.\n\
             # OMNION_BASE_URL=\n# OMNION_TOKEN=\n",
        ),
        gitignore(),
        readme(
            name,
            ScaffoldKind::Plugin,
            "Build with `npm install && npm run build`, then install the folder through the \
             extensions screen.",
        ),
    ]
}

// ───────────────────────────────────────────────────────────────── theme

fn theme(name: &str, target: ScaffoldTarget) -> Vec<ScaffoldFile> {
    // The target is recorded on the generation row and deliberately does not change a byte of
    // the generated tree -- see `ScaffoldTarget`'s doc. Reading it here keeps the parameter
    // honest for a future per-target template without pretending one exists today.
    let _aimed_at = target;
    let title = title_case(name);
    vec![
        ScaffoldFile::new(
            "omnion.manifest.json",
            manifest(ScaffoldKind::Theme, name, "dist/theme.js", &title),
        ),
        ScaffoldFile::new(
            "src/theme.ts",
            format!(
                "// {title} — a theme template.\n\
                 //\n\
                 // A theme contributes templates and section renderers. The platform owns the\n\
                 // page; you decide what a slot inside it looks like.\n\
                 import type {{ ThemeContext }} from \"@omnion/sdk\";\n\n\
                 export function activate(context: ThemeContext) {{\n\
                 \x20 context.templates.register(\"{{content}}\", contentTemplate);\n\
                 \x20 context.sections.register(\"hero\", heroSection);\n\
                 }}\n\n\
                 function contentTemplate({{ entry }}: {{ entry: {{ title: string; body: string }} }}) {{\n\
                 \x20 return `<article class=\"entry\">\n    <h1>${{entry.title}}</h1>\n    \
                 \x20   <div class=\"body\">${{entry.body}}</div>\n  </article>`;\n\
                 }}\n\n\
                 function heroSection(props: {{ heading: string; text?: string }}) {{\n\
                 \x20 return `<header class=\"hero\">\n    <h2>${{props.heading}}</h2>\n    \
                 \x20   ${{props.text ? `<p>${{props.text}}</p>` : \"\"}}\n  </header>`;\n\
                 }}\n",
                title = title,
            ),
        ),
        ScaffoldFile::new(
            "src/styles.css",
            "/* {title} */\n:root {\n  --theme-accent: #4f46e5;\n  \
             --theme-text: #111827;\n}\n\n.entry {\n  max-width: 42rem;\n  \
             margin-inline: auto;\n}\n\n.hero h2 {\n  font-size: 1.75rem;\n}\n",
        ),
        ScaffoldFile::new(
            "package.json",
            format!(
                "{{\n  \"name\": \"{name}\",\n  \"version\": \"1.0.0\",\n  \"private\": true,\n  \
                 \"type\": \"module\",\n  \"main\": \"dist/theme.js\",\n  \
                 \"scripts\": {{\n    \"build\": \"tsc -p tsconfig.json\",\n    \
                 \"check\": \"tsc -p tsconfig.json --noEmit\"\n  }},\n  \
                 \"devDependencies\": {{\n    \"@omnion/sdk\": \"^1.0.0\",\n    \
                 \"typescript\": \"^5.0.0\"\n  }}\n}}\n"
            ),
        ),
        ScaffoldFile::new(
            "tsconfig.json",
            "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \"module\": \"ES2022\",\n    \
             \"moduleResolution\": \"bundler\",\n    \"strict\": true,\n    \"outDir\": \"dist\",\n    \
             \"declaration\": true\n  },\n  \"include\": [\"src\"]\n}\n",
        ),
        gitignore(),
        readme(
            name,
            ScaffoldKind::Theme,
            "A theme renders content the platform already stores. It does not define the content \
             types.",
        ),
    ]
}

// ───────────────────────────────────────────────────────────────── workflow

fn workflow(name: &str, target: ScaffoldTarget) -> Vec<ScaffoldFile> {
    // The target is recorded on the generation row and deliberately does not change a byte of
    // the generated tree -- see `ScaffoldTarget`'s doc. Reading it here keeps the parameter
    // honest for a future per-target template without pretending one exists today.
    let _aimed_at = target;
    let title = title_case(name);
    vec![
        ScaffoldFile::new(
            "omnion.manifest.json",
            manifest(ScaffoldKind::Workflow, name, "workflow.omni", &title),
        ),
        ScaffoldFile::new(
            "workflow.omni",
            format!(
                "# {title}\n\
                 #\n\
                 # A workflow is a trigger, some steps and their edges. Run it from the automation\n\
                 # screen after installing the folder.\n\n\
                 trigger manual\n\
                 \n\
                 step greet:\n\
                 \x20 log \"{title} ran for ${{{{ trigger.actor }}}}\"\n\n\
                 step notify:\n\
                 \x20 log \"finished at ${{{{ steps.greet.output }}}}\"\n\n\
                 greet -> notify\n",
                title = title,
            ),
        ),
        ScaffoldFile::new(
            "README.md",
            format!(
                "# {title}\n\n\
                 A workflow starter generated by Omnion.\n\n\
                 `workflow.omni` is the whole workflow. It declares a manual trigger, two steps and\n\
                 the edge between them. Open it in the workflow builder to add nodes visually, or\n\
                 edit the file directly and reinstall.\n\n\
                 ## Do not commit credentials\n\n\
                 If you add a credential node, put the credential in the platform's secrets\n\
                 manager and reference it by name. Do not paste a token into this file — it gets\n\
                 copied into public repositories.\n",
                title = title,
            ),
        ),
        gitignore(),
        env_example(),
    ]
}

// ───────────────────────────────────────────────────────────────── helpers

/// Turn `my-plugin` into `My Plugin` for the display name.
///
/// ASCII-only on purpose: a name is validated as a slug, so it can only contain ASCII letters,
/// digits, `-` and `_`. Mapping `_` to a space here would be wrong (it is a valid name
/// character, not a word break) so only dashes break.
fn title_case(name: &str) -> String {
    name.split('-')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every kind, every name shape, generated and checked against the rules.
    #[test]
    fn every_kind_generates_a_tree_with_a_manifest_a_readme_and_a_gitignore() {
        for kind in ScaffoldKind::ALL {
            let scaffold = generate(kind, "hello-world", ScaffoldTarget::Live).unwrap();
            let paths: Vec<&str> = scaffold.files.iter().map(|f| f.path.as_str()).collect();
            assert!(
                paths.contains(&"omnion.manifest.json"),
                "{kind:?} ships no manifest: {paths:?}"
            );
            assert!(paths.contains(&"README.md"), "{kind:?} ships no README");
            assert!(
                paths.contains(&".gitignore"),
                "{kind:?} ships no .gitignore"
            );
        }
    }

    /// The two properties the panel's file-tree preview depends on.
    #[test]
    fn the_byte_total_equals_the_sum_of_the_files_and_is_not_zero() {
        let scaffold = generate(ScaffoldKind::Plugin, "hello-world", ScaffoldTarget::Live).unwrap();
        let sum: usize = scaffold.files.iter().map(|f| f.content.len()).sum();
        assert_eq!(scaffold.byte_size, sum);
        assert!(
            scaffold.byte_size > 500,
            "a starter this small cannot be useful"
        );
    }

    #[test]
    fn the_hidden_files_are_generated_but_not_offered_for_preview() {
        // Both halves matter. `.gitignore` exists because the risk note asks for it; it is
        // hidden because a preview full of dotfiles is noise. `.env.example` is the same kind
        // of file but the README points at it, so hiding it would hide the warning's target.
        let scaffold = generate(ScaffoldKind::Plugin, "hello-world", ScaffoldTarget::Live).unwrap();
        for file in &scaffold.files {
            if file.path == ".gitignore" {
                assert!(!file.shown_in_preview);
                assert!(!file.content.is_empty());
            }
        }
    }

    /// The rule that makes this module exist. Review catches what you are looking at; this
    /// catches what you add afterwards.
    #[test]
    fn no_template_looks_like_it_carries_a_credential() {
        // Patterns a secret scanner would flag, and that a reader skimming a starter would
        // mistake for a real value. `OMNION_TOKEN=` on its own line is *not* here: an empty
        // assignment is the thing we want, and the presence of the name is the warning.
        const FORBIDDEN: [&str; 8] = [
            "sk_live_",
            "sk_test_",
            "ghp_",
            "gho_",
            "github_pat_",
            "xoxb-",
            "xoxp-",
            "AKIA",
        ];
        for kind in ScaffoldKind::ALL {
            let scaffold = generate(kind, "hello-world", ScaffoldTarget::Sandbox).unwrap();
            for file in &scaffold.files {
                for needle in FORBIDDEN {
                    assert!(
                        !file.content.contains(needle),
                        "{kind:?}/{} looks like it carries a credential ({needle})",
                        file.path
                    );
                }
            }
        }
    }

    /// The empty-value half of the same rule, stated separately.
    ///
    /// A `.env.example` whose keys are *populated* is the failure. Asserting it is empty is the
    /// only way that stays true when someone helpfully fills in the base URL.
    #[test]
    fn the_example_environment_file_has_names_and_no_values() {
        let scaffold =
            generate(ScaffoldKind::Workflow, "hello-world", ScaffoldTarget::Live).unwrap();
        let env = scaffold
            .files
            .iter()
            .find(|file| file.path == ".env.example")
            .expect("the workflow template ships an example environment file");
        for line in env.content.lines() {
            let line = line.trim();
            if let Some((key, value)) = line.split_once('=') {
                assert!(
                    value.is_empty(),
                    ".env.example assigns a value to {key:?}: {value:?}"
                );
            }
        }
    }

    /// The generated manifest is valid by the rule the loader uses — see the scaffold tests,
    /// which assert the same property across all three kinds. This one states the reason: a
    /// template that failed its own validator would make the panel's green Validate button
    /// meaningless.
    #[test]
    fn a_generated_manifest_validates() {
        let scaffold = generate(ScaffoldKind::Theme, "hello-world", ScaffoldTarget::Live).unwrap();
        let manifest = scaffold
            .files
            .iter()
            .find(|file| file.path == "omnion.manifest.json")
            .unwrap();
        let report = crate::scaffold::validate_manifest(ScaffoldKind::Theme, &manifest.content);
        assert!(report.valid, "{:?}", report.issues);
    }

    #[test]
    fn the_slug_appears_verbatim_in_the_manifest() {
        // The failure this prevents: a manifest whose name differs from the directory name,
        // which is an extension that installs as one thing and reports as another.
        for name in ["my-plugin", "a_b", "x1-y2"] {
            let scaffold = generate(ScaffoldKind::Plugin, name, ScaffoldTarget::Live).unwrap();
            let manifest = &scaffold.files[0];
            assert!(
                manifest.content.contains(&format!("\"name\": \"{name}\"")),
                "manifest does not carry {name:?}"
            );
            assert_eq!(scaffold.slug(), format!("plugin-{name}"));
        }
    }

    #[test]
    fn the_display_name_is_the_slug_in_readable_form() {
        let scaffold = generate(
            ScaffoldKind::Plugin,
            "my-first-plugin",
            ScaffoldTarget::Live,
        )
        .unwrap();
        let manifest = &scaffold.files[0];
        assert!(
            manifest
                .content
                .contains("\"displayName\": \"My First Plugin\""),
            "{}",
            manifest.content
        );
    }

    #[test]
    fn generation_refuses_an_invalid_name_before_it_builds_anything() {
        // The gate is in the generator, not only in the handler — so a future second caller
        // cannot skip it.
        assert!(generate(ScaffoldKind::Plugin, "../escape", ScaffoldTarget::Live).is_err());
        assert!(generate(ScaffoldKind::Plugin, "", ScaffoldTarget::Live).is_err());
    }

    #[test]
    fn the_target_does_not_change_a_byte_of_the_output() {
        // The claim the `ScaffoldTarget` doc makes. If a future change breaks it, the two
        // starters it produces are wrong in one environment, which is the thing the doc says
        // is the reason they are identical.
        let live = generate(ScaffoldKind::Plugin, "hello-world", ScaffoldTarget::Live).unwrap();
        let sandbox =
            generate(ScaffoldKind::Plugin, "hello-world", ScaffoldTarget::Sandbox).unwrap();
        let live: Vec<&str> = live.files.iter().map(|f| f.content.as_str()).collect();
        let sandbox: Vec<&str> = sandbox.files.iter().map(|f| f.content.as_str()).collect();
        assert_eq!(live, sandbox);
    }
}
