-- Omnion · 0032 · Secret access audit depth, anomaly flags and the SIEM feed
-- (REQ-125, slice 4 · docs/requests/REQ-125-secrets-management-depth.md).
--
-- Additive by design (docs/05-VERSIONING.md): three new tables, four nullable columns on an
-- existing one. No table is rewritten, no column is dropped, and every existing row keeps its
-- meaning — a column that is null means "this audit row predates the column", not "unknown".
--
-- The request says "the REQ-037 access log is extended additively". REQ-037 is still queued and
-- its table does not exist yet, so there is nothing to extend — and inventing a second
-- secrets-specific ledger now would leave REQ-037 with a parallel table to reconcile later.
-- The platform already has exactly the structure this needs: `audit_log` (0001) is append-only,
-- carries the actor, the organization, the peer address and a metadata object, and every
-- secrets operation already writes to it through `omnion_audit::entries::record`. So this
-- migration deepens *that* trail instead of duplicating it. "One ledger" is the same rule the
-- request states about redaction: two implementations drift.
--
-- What a generic trail lacks, and what these columns add, is the vocabulary of a secret
-- operation: which lease, which deployment key, which pipeline, and the request id the caller
-- was given in its error banner. Without a request id an operator holding a refusal can never
-- join it to the row that explains it; with one, the whole trail is joinable. `request_id` is
-- therefore generated by the handler and written to *both* places — the error details and this
-- column — rather than read from a header the platform does not set.
--
-- Numbering note: the slot is global across the parallel waves and 0031 was already claimed by
-- wave 4's CRM search providers, so the file was named from `ls` of the sibling worktrees at
-- write time, not from a counter that pretends the branch is alone.

-- ── the four columns the request names ───────────────────────────────────────────────────────────
--
-- All four are nullable and none has a default, which is the whole point: a row that was
-- written before this migration must keep working, and the only honest value for "this row was
-- not part of a lease" on an old row is null.
alter table audit_log
    add column request_id        uuid,
    add column lease_id          uuid,
    add column deployment_key_id uuid,
    add column pipeline          text;

comment on column audit_log.request_id is
    'The id handed back to the caller in the error details, so a refusal and the row that '
    'explains it are joinable. Null on rows written before 0032.';
comment on column audit_log.lease_id is
    'The credential lease the operation touched (issue, redeem, revoke).';
comment on column audit_log.deployment_key_id is
    'The machine identity that spent the operation, when the actor was a deployment key.';
comment on column audit_log.pipeline is
    'The pipeline identity presented by the machine, as text, for the same reason a use log '
    'records it: a leaked key is traced to a pipeline name.';

-- The SIEM feed reads a bounded, recent slice by time; the audit screen filters by action and
-- by secret. The action index 0001 already has covers the first, so only the second is new —
-- and it is a partial index because the overwhelming majority of `audit_log` rows are not
-- secrets rows and a full index on `(target_type, target_id)` would tax every other writer's
-- inserts to speed up one screen.
create index audit_log_secret_target_idx
    on audit_log (target_id, created_at desc)
    where target_type = 'secret' and target_id is not null;

-- ── anomaly flags ────────────────────────────────────────────────────────────────────────────────
--
-- An anomaly is an *advisory record*, never a gate. The request is explicit that one optional
-- hard rule may block, and that it ships off; the reasoning matters more than the schema: a
-- hard rule that blocks a reveal can lock an incident responder out at the worst moment, and
-- the cost of that is higher than the cost of an extra advisory row nobody reads. So
-- `severity` exists on the row, the acknowledge action exists on the row, and nothing in this
-- schema can refuse a reveal. The one column that *could* become a gate — `hard_rule_enforced`
-- in the settings table below — defaults to false and is read by nobody in this migration.
create table secret_audit_anomalies (
    id             bigserial   primary key,
    organization_id uuid       references organizations (id) on delete cascade,
    -- The secret the pattern was seen on; a pattern that is about the *actor* alone (a burst,
    -- a new network) still names the secret it was observed on so the screen can group it.
    secret_id      uuid        references secrets (id) on delete cascade,
    -- `off_hours_reveal`, `reveal_burst`, `new_network` or `unfamiliar_principal`.
    pattern        text        not null,
    -- `advisory` today; `blocking` exists so the optional hard rule of the request has a place
    -- to live when an operator deliberately turns it on.
    severity       text        not null default 'advisory',
    -- The actor the pattern was observed on, so a burst is attributed rather than anonymous.
    actor_user_id  uuid        references users (id) on delete set null,
    -- The peer address the observation was made from.
    address        inet,
    -- What the detector saw: the hour, the count, the window, the known networks. Never a
    -- value and never a masked fragment — the redaction rule of the request applies to the
    -- detail object exactly as it applies to a response body.
    detail         jsonb       not null default '{}'::jsonb,
    -- The request id of the operation that triggered it, so the flag joins to the trail.
    request_id     uuid,
    acknowledged_by uuid       references users (id) on delete set null,
    acknowledged_at timestamptz,
    created_at     timestamptz not null default now(),
    constraint secret_audit_anomalies_pattern_check
        check (pattern in ('off_hours_reveal', 'reveal_burst', 'new_network', 'unfamiliar_principal')),
    constraint secret_audit_anomalies_severity_check
        check (severity in ('advisory', 'blocking'))
);

comment on table secret_audit_anomalies is
    'Advisory records raised by the reveal detectors of REQ-125. Nothing here blocks an '
    'operation: a rule that can lock an incident responder out costs more than an unread row.';

-- The screen reads the unacknowledged flags first, newest first, and the acknowledge action
-- updates one row. A partial index over the *live* set keeps that read proportional to what
-- actually needs attention rather than to the whole history — the same reason the lease table
-- indexes only its live rows.
create index secret_audit_anomalies_live_idx
    on secret_audit_anomalies (created_at desc) where acknowledged_at is null;

-- The detector for a burst counts reveals in a window, and the detector for an unfamiliar
-- principal asks whether this actor ever touched this secret before. Both are point reads on
-- `audit_log`, so both need the same index the audit screen's secret filter uses — the one
-- created above covers `(target_id, created_at desc)`.
--
-- A note on what deliberately has no index: `unfamiliar_principal` is answered by
-- "has this actor revealed this secret before", which the index above serves. The tempting
-- alternative — an index on `(actor_user_id, target_id)` — would double the insert tax on
-- every audited action in the platform to answer a question asked once per reveal.

-- ── detector thresholds ──────────────────────────────────────────────────────────────────────────
--
-- One settings row per installation. The request puts the thresholds here rather than in code,
-- and the reason is that a threshold in code is a threshold nobody can raise: an operator whose
-- business runs overnight would otherwise have to ship a patch to stop the off-hours detector
-- from crying wolf every night.
create table secret_audit_settings (
    id                    boolean     primary key default true,
    -- Local hours [start, end) that count as business hours. Wrapping ranges (22 → 6) are legal
    -- and mean what an operator expects: the overnight shift.
    business_hours_start  smallint    not null default 8,
    business_hours_end    smallint    not null default 19,
    -- How many reveals of one secret in an hour count as a burst.
    reveal_burst_per_hour integer     not null default 10,
    -- "Production reveals require a second approver" is the request's example of a hard rule.
    -- It exists, it defaults off, and this migration reads it nowhere.
    hard_rule_enforced    boolean     not null default false,
    -- Whether a reveal from an address never seen before is flagged.
    detect_new_network    boolean     not null default true,
    updated_by            uuid        references users (id) on delete set null,
    updated_at            timestamptz not null default now(),
    constraint secret_audit_settings_singleton_check check (id),
    constraint secret_audit_settings_hours_check
        check (business_hours_start between 0 and 23 and business_hours_end between 0 and 23)
);

comment on table secret_audit_settings is
    'Detector thresholds for the secrets audit. A threshold in code is a threshold nobody can '
    'raise without shipping a patch, which is why business hours are data.';

insert into secret_audit_settings (id) values (true)
on conflict (id) do nothing;

-- Reversal, in the order REQ-129's policy asks for: drop what this file created, nothing else.
--
--   drop table if exists secret_audit_settings;
--   drop table if exists secret_audit_anomalies;
--   drop index if exists audit_log_secret_target_idx;
--   alter table audit_log
--       drop column if exists pipeline,
--       drop column if exists deployment_key_id,
--       drop column if exists lease_id,
--       drop column if exists request_id;
--
-- The columns are dropped last and separately because a downgrade that removed the tables but
-- kept the columns would leave `audit_log` referencing a lease that no longer has a table.
--
-- A note on the index this file deliberately does *not* create. The obvious addition is a
-- "recent reveals" index for the burst detector:
--
--   create index on audit_log (created_at desc) where action = 'secret.revealed';
--
-- and it is wrong twice over. Partial index predicates may not compare against a value that is
-- not a column, so `action = '…'` is legal but the index would have to be rebuilt by hand
-- whenever the action name changed; and `audit_log_action_idx` (0001) already covers `action`,
-- so a combined scan of that index with the time range is a two-index read the planner can do
-- anyway. The window a burst detector scans is one hour.
