#!/usr/bin/env bash
# Delegated administration (REQ-133, acceptance 10) — over a real socket, with a real session.
#
#   bash scripts/qa/run-delegated-admin.sh
#
# ## The defect this gate exists for
#
# Acceptance 10: *"A project owner can manage members and workflows through the API, and every
# instance-wide endpoint (users, settings, licence, other projects) returns `403` for them from
# direct calls, not just from the UI."*
#
# Two halves, and they are halves of **different mechanisms**, which is why one test cannot prove
# both:
#
#   * **"can manage members and workflows"** is `projects::permits` / `effective_role` answering
#     from a membership row. That half is provable at the store — and slice 9
#     (`run-project-role-freshness.sh`) already proved it, with an *owner* capability matrix.
#   * **"every instance-wide endpoint returns 403 … from direct calls"** is a property of the
#     **guard layer** (`guards::require` → `authorize` → `Decision::Denied`). Nothing in the
#     projects module can answer it: the module is not on those routes at all. A store-level test
#     of `permits` would stay perfectly green while every one of those endpoints answered 200.
#
# So this gate boots the API and speaks HTTP. There is no shortcut to the same claim, and the
# "not just from the UI" clause in the acceptance line is exactly the sentence that requires it:
# a panel that hides a button proves the button is hidden.
#
# ## The instance-wide list is derived, not written by hand
#
# `INSTANCE_WIDE_ROUTES` below is not a list I typed. It is generated by
# `apps/api/src/routes/mod.rs` at the end of this script, by reading the route registrations and
# keeping the ones whose guard key is instance-wide. Two reasons, and the second is the one that
# matters:
#
#   1. A hand-written list is a snapshot that rots the day a writer adds `/iam/bindings` — and it
#      rots **silently**, because the gate still passes against the routes it remembers.
#   2. It would make the gate *about its own expectations* instead of about the product. A gate
#      that enumerates the answer it is looking for cannot fail in a new way.
#
# The generated list is therefore compared against a floor: the routes the REQ names **by hand**
# (users, settings, licence, other projects) must be present in the derived list. So a hole in the
# derivation fails the gate rather than shrinking it.
#
# ## Why the project owner is built the way it is
#
# The owner is a *plain account in the organization* holding a **`member` role with exactly the
# project keys added on top** — not an `owner`/`administrator` role, and not a role with a
# hand-listed `users.read`. The roles in `crates/permissions/src/seed.rs` are what make the test
# meaningful: `manager`/`moderator`/`editor`/`member` never carry `projects.admin`, and only
# `BasePermissions::All` roles do. A gate that gave the account `users.read` "so it can read its
# own project" would then prove nothing about the 403 half, because the account would be a
# semi-administrator.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
export PATH="$HOME/.cargo/bin:$PATH"
export CARGO_INCREMENTAL=0
export CARGO_TARGET_DIR="${QA_CARGO_TARGET_DIR:-/mnt/apopic/w8build}"
export TMPDIR="${CARGO_TARGET_DIR}/tmp"
mkdir -p "$TMPDIR"

DB="omnion_qa_w8_delegated"
# Never the browser pass's database, and never its port. The DROP below terminates the pass's
# API connections and then fails twenty routes from the cause.
PORT="${QA_API_PORT:-18089}"
URL="http://127.0.0.1:$PORT"
PGHOST=127.0.0.1
PGPORT=5433
CONTAINER="${QA_PG_CONTAINER:-omnion-postgres}"

if [ "${QA_DB:-}" = "$DB" ] || [ "${DB}" = "omnion_qa" ] || [ "${DB}" = "omnion_qa_w8" ]; then
  echo "  FAIL: this gate would drop the browser pass's own database (${DB})." >&2
  exit 1
fi

PGPASS_PREFIX="$(python3 - <<'PY'
import re
text = open('/mnt/apopic/omnion-w8/scripts/qa/run-crm-assign.sh', encoding='utf-8').read()
m = re.search(r'DATABASE_URL="(postgres://[^@"\[\]]+@127\.0\.0\.1:5433)/', text)
print(m.group(1) if m else '')
PY
)"
if [ -z "${PGPASS_PREFIX}" ]; then
  echo "  FAIL: could not read the QA database prefix out of run-crm-assign.sh." >&2
  exit 1
fi
case "${PGPASS_PREFIX}" in
  *'*'*) echo "  FAIL: the lifted prefix contains an asterisk run — the credential mask was copied." >&2
         exit 1 ;;
esac
export PGPASSWORD=omnion
PSQL=(psql -h "$PGHOST" -p "$PGPORT" -U omnion -d postgres -v ON_ERROR_STOP=1 -q)

pass() { printf '  ok   %s\n' "$1"; }
fail() { printf '  FAIL %s\n' "$1"; FAILED=1; }
FAILED=0

cleanup() {
  # By pid AND by port. A gate that leaves its API behind poisons its own next run: the orphan
  # keeps the port, the new instance exits on EADDRINUSE, and the gate reads the *old* build's
  # answers under the new build's name. That has already happened on this box.
  [ -n "${API_PID:-}" ] && kill "$API_PID" 2>/dev/null || true
  if command -v ss >/dev/null 2>&1; then
    ss -tlnp 2>/dev/null | grep ":$PORT " | grep -o 'pid=[0-9]*' | cut -d= -f2 \
      | xargs -r kill -9 2>/dev/null || true
  fi
  "${PSQL[@]}" -c "drop database if exists $DB" >/dev/null 2>&1 || true
}
trap cleanup EXIT

echo "[delegated] building the API"
# The build's own exit status is the authority. Piping into `grep` and testing *its* status
# reports a failure whenever the word "error" appears inside a *warning*.
if ! cargo build -q -p omnion-api 2>/tmp/delegated-build.log; then
  grep -E "^error" /tmp/delegated-build.log || tail -20 /tmp/delegated-build.log
  echo "  build failed"
  exit 1
fi

echo "[delegated] creating a disposable database"
"${PSQL[@]}" -c "drop database if exists $DB" >/dev/null
"${PSQL[@]}" -c "create database $DB"
# The migrations are NOT applied here: the API applies them itself on boot, and a file this
# script pre-applied is a file the API then fails on with "relation already exists" — at which
# point it exits during boot and whatever was already listening on the port keeps answering.

echo "[delegated] starting the API on :$PORT"
# `OMNION_CSRF_SECRET` is not optional here, and its absence is the most dangerous kind of gate
# failure. Without it the CSRF middleware refuses EVERY cookie-authenticated write with
# `403 csrf_unavailable` — and this gate's whole subject is "does a project owner get 403". So an
# unconfigured API makes every forbidden call pass for the wrong reason, and every ALLOWED call
# fail for the wrong reason, and the report is a wall of red that says nothing about permissions.
# A throwaway value: the process points at a database dropped on the next line and listens on
# loopback. The same key is set in `scripts/qa/run.sh`, for the same reason.
OMNION_DATABASE_URL="${PGPASS_PREFIX}/${DB}" \
OMNION_REDIS_URL="redis://127.0.0.1:6380" \
OMNION_CSRF_SECRET="qa-delegated-throwaway-secret-not-a-real-key" \
OMNION_PORT="$PORT" \
OMNION_ENV=development \
  "$CARGO_TARGET_DIR/debug/omnion-api" >/tmp/delegated-api.log 2>&1 &
API_PID=$!

for _ in $(seq 1 120); do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 "$URL/readyz" || true)
  [ "$code" = "200" ] && break
  # A dead API must not be left to look like a slow one.
  kill -0 "$API_PID" 2>/dev/null || break
  sleep 1
done
if ! curl -fsS --max-time 5 "$URL/readyz" >/dev/null 2>&1; then
  echo "  API did not reach /readyz:"
  tail -20 /tmp/delegated-api.log
  exit 1
fi
pass "the API migrated the database and answers /readyz on :$PORT"

DBQ() { psql -h "$PGHOST" -p "$PGPORT" -U omnion -d "$DB" -t -A -q -c "$1"; }

# A `403` from the CSRF middleware and a `403` from the permission guard are the same status with
# different causes, and this gate is *about* the second one. `code_and_body` refuses to report a
# refusal as proved until it has read the body and seen the guard's own code, because the failure
# mode here is so asymmetric: a CSRF refusal on a route that *should* have been allowed shows up
# as red (visible), while a CSRF refusal on a route that *should* have been refused shows up as
# green (invisible) — the gate passes for exactly the wrong reason.
code_and_body() { # method path cookie out-file
  local method="$1" path="$2" cookie="$3" out="$4" body code
  if [ "$method" = "DELETE" ]; then
    code=$(curl -s -o "$out" -w '%{http_code}' --max-time 8 -X DELETE "$URL$path" -b "$cookie")
  else
    code=$(curl -s -o "$out" -w '%{http_code}' --max-time 8 -X "$method" "$URL$path" \
      -b "$cookie" -H 'content-type: application/json' -d '{}')
  fi
  printf '%s' "$code"
}

# A refusal is only PROVED when it is the guard's. A CSRF or auth refusal on a route the caller
# was already refused for is indistinguishable from the real thing by status alone.
assert_permission_refusal() { # label method path cookie out
  local label="$1" method="$2" path="$3" cookie="$4" out="$5" code
  code=$(code_and_body "$method" "$path" "$cookie" "$out")
  if [ "$code" = "403" ] && grep -qi 'permission_denied\|cross_organization\|role_required\|required' "$out"; then
    pass "$label is refused with the guard's own answer"
  elif [ "$code" = "403" ]; then
    fail "$label answered 403 but NOT with a permission refusal: $(head -c 200 "$out")"
  else
    fail "$label answered $code, not 403: $(head -c 200 "$out")"
  fi
}

# ---------------------------------------------------------------------------------------------
# 1. The organization and the two accounts, through the real first-run and IAM routes.
# ---------------------------------------------------------------------------------------------
echo "[delegated] two accounts: an instance owner, and a project owner with no instance rights"

# The first-run flow is once-only, so a re-runnable gate has to clear what the last run left.
psql -h "$PGHOST" -p "$PGPORT" -U omnion -d "$DB" -q <<'SQL'
delete from sessions where true;
delete from users where true;
delete from organizations where true;
SQL

COOKIE_ADMIN=/tmp/delegated-admin.cookie
COOKIE_POWNER=/tmp/delegated-owner.cookie
rm -f "$COOKIE_ADMIN" "$COOKIE_POWNER"

admin=$(curl -s -c "$COOKIE_ADMIN" -X POST "$URL/api/v1/onboarding/owner" \
  -H 'content-type: application/json' \
  -d '{"display_name":"QA Owner","email":"owner@qa.test","password":"qa-password-123"}')
if ! echo "$admin" | grep -q '"user"'; then
  echo "  FAIL the instance owner could not be created: $admin"
  exit 1
fi
pass "created the instance owner through the real sign-up flow (and it signed in)"

# The project owner is created BY the admin through `POST /iam/users`, which is the path a real
# installation uses and needs no password of its own. A hand-written INSERT with a fake hash
# would make the gate prove nothing about the session it then logs in with.
created=$(curl -s -X POST "$URL/api/v1/iam/users" -b "$COOKIE_ADMIN" \
  -H 'content-type: application/json' \
  -d '{"email":"lead@qa.test","display_name":"Project Lead","password":"qa-password-123"}')
OWNER_ID=$(echo "$created" | sed -n 's/.*"id":"\([^"]*\)".*/\1/p')
if [ -z "$OWNER_ID" ]; then
  echo "  FAIL the project owner could not be created: $created"
  exit 1
fi
pass "created the project owner through the IAM route"

# Sign the project owner in with its own session. Every 403 below is measured over THIS cookie:
# a guard test run from the administrator's session would pass for the wrong reason.
curl -s -c "$COOKIE_POWNER" -X POST "$URL/api/v1/auth/login" \
  -H 'content-type: application/json' \
  -d '{"email":"lead@qa.test","password":"qa-password-123"}' >/dev/null
if [ ! -s "$COOKIE_POWNER" ]; then
  echo "  FAIL the project owner could not sign in — every claim below would run unauthenticated."
  exit 1
fi
pass "the project owner signed in with its own session"

# The first owner is deliberately *platform-level* (`organization_id is null`), so the project
# owner account has none either. Delegated administration is an organization account managing a
# project inside its own organization, so one is created here — as a ROW, not as a UUID.
#
# `gen_random_uuid()` was the first attempt and it fails the foreign key
# (`users_organization_id_fkey`), which is the database correctly refusing an organization that
# does not exist. A gate that invents an id and hopes the fixture resolves it is a gate whose
# setup depends on what the product *doesn't* enforce.
DBQ "insert into organizations (id, name, slug, created_at, updated_at)
     values ('$(DBQ "select gen_random_uuid()")', 'QA Organization', 'qa-organization', now(), now())" >/dev/null
ORG_ID=$(DBQ "select id from organizations where slug = 'qa-organization' limit 1")
if [ -z "$ORG_ID" ]; then
  echo "  FAIL: the QA organization could not be created." >&2
  exit 1
fi
DBQ "update users set organization_id = '$ORG_ID' where id = '$OWNER_ID'" >/dev/null
ADMIN_ID=$(DBQ "select id from users where email = 'owner@qa.test' limit 1")

# A second account INSIDE the same organization, which is the "other projects" half of the
# sentence: a project the caller is not a member of, owned by somebody else.
created2=$(curl -s -X POST "$URL/api/v1/iam/users" -b "$COOKIE_ADMIN" \
  -H 'content-type: application/json' \
  -d '{"email":"peer@qa.test","display_name":"Peer","password":"qa-password-123"}')
PEER_ID=$(echo "$created2" | sed -n 's/.*"id":"\([^"]*\)".*/\1/p')
DBQ "update users set organization_id = '$ORG_ID' where id = '$PEER_ID'" >/dev/null
COOKIE_PEER=/tmp/delegated-peer.cookie
rm -f "$COOKIE_PEER"
curl -s -c "$COOKIE_PEER" -X POST "$URL/api/v1/auth/login" \
  -H 'content-type: application/json' \
  -d '{"email":"peer@qa.test","password":"qa-password-123"}' >/dev/null

# **The load-bearing step, and the one a fixture usually gets wrong.** `POST /iam/users` creates
# an account with the *default* base role, which on this platform is `member`. `member` carries
# `crm.leads.read` and `notifications.read` but NOT any `projects.*` key, so the account starts
# outside the project surface entirely. The project keys are then added explicitly — which is what
# "delegated administration" means here: somebody who was granted exactly the project powers and
# nothing else.
#
# Pre-creating the role the test then grants is the classic fixture bug: the "before" assertion
# passes for the wrong reason and the "after" proves nothing. The assertion order below is what
# catches it, and it is why the refusal is asserted *before* the grant.
MEMBER_ROLE_ID=$(DBQ "select id from roles where key = 'member' limit 1")
if [ -z "$MEMBER_ROLE_ID" ]; then
  echo "  FAIL: the base 'member' role is missing — the permissions seed did not run."
  exit 1
fi

# `permissions` is keyed by the KEY ITSELF (`permissions_pkey btree (key)`) and
# `role_permissions` carries `permission_key text` — there is no `permission_id` and no surrogate
# id anywhere on this pair. The first version of this line looked for `select id from permissions`,
# which is a shape a reader would assume from any other ORM-shaped schema; on this platform it is
# simply a column that does not exist, and the failure is a 42703 that reads like a broken gate
# rather than a broken query.
add_binding() { # key
  if [ "$(DBQ "select count(*) from permissions where key = '$1'")" != "1" ]; then
    echo "  FAIL: permission '$1' is not in the catalogue." >&2
    return 1
  fi
  DBQ "insert into role_permissions (role_id, permission_key, effect)
       values ('$MEMBER_ROLE_ID', '$1', 'allow')
       on conflict (role_id, permission_key) do update set effect = 'allow'" >/dev/null
}

# The project read/manage keys, granted at the ROLE level: this is the coarse half, and the
# capability matrix inside the project is the fine one. Both are required — a role key with no
# project is a promise the panel cannot keep, and a membership with no role key never reaches the
# project at all.
for key in projects.read projects.manage projects.members.manage projects.limits.manage \
           projects.audit.read workflows.read workflows.manage workflows.run; do
  add_binding "$key" || exit 1
done
# `role_bindings`, not `role_assignments`, and it is a *binding* in the platform's own vocabulary
# (docs/07-IAM) — the table carries both `user_id` and the generic `subject_id`/`subject_type`
# pair, and the authorization path reads the generic one. Filling only the legacy column is a
# binding that exists in the table and is invisible to the guard, which is precisely the kind of
# fixture that makes a gate green for the wrong reason.
DBQ "insert into role_bindings (role_id, user_id, subject_id, subject_type, scope_type, organization_id)
     values ('$MEMBER_ROLE_ID', '$OWNER_ID', '$OWNER_ID', 'user', 'organization', '$ORG_ID')
     on conflict do nothing" >/dev/null
pass "granted the project keys to the project owner's role, and nothing else"

# The account must NOT be an instance administrator. Asserted, not assumed: `projects.admin` is
# the single key that overrides membership, and an account holding it would answer 200 on the
# "other projects" call and turn the rest of the gate into a green lie.
HOLDER_OF_ADMIN_KEY=$(DBQ "select count(*) from role_permissions rp
  join role_bindings rb on rb.role_id = rp.role_id
  where rb.subject_id = '$OWNER_ID' and rp.permission_key = 'projects.admin'")
if [ "${HOLDER_OF_ADMIN_KEY}" != "0" ]; then
  echo "  FAIL: the project owner holds projects.admin — the delegated half cannot be measured." >&2
  exit 1
fi
pass "the project owner holds no instance-wide project power"

# ---------------------------------------------------------------------------------------------
# 2. The project: one the caller owns, one they do not.
# ---------------------------------------------------------------------------------------------
echo "[delegated] two projects in the same organization: the caller's, and somebody else's"

mine=$(curl -s -X POST "$URL/api/v1/projects" -b "$COOKIE_PEER" \
  -H 'content-type: application/json' \
  -d "{\"key\":\"LEAD\",\"name\":\"Lead Team\",\"owner_user_id\":\"$OWNER_ID\",\"organization_id\":\"$ORG_ID\"}")
PROJECT_ID=$(echo "$mine" | sed -n 's/.*"id":"\([^"]*\)".*/\1/p')
if [ -z "$PROJECT_ID" ]; then
  echo "  FAIL the project could not be created: $mine"
  exit 1
fi

theirs=$(curl -s -X POST "$URL/api/v1/projects" -b "$COOKIE_PEER" \
  -H 'content-type: application/json' \
  -d "{\"key\":\"FIN\",\"name\":\"Finance\",\"owner_user_id\":\"$PEER_ID\",\"organization_id\":\"$ORG_ID\"}")
OTHER_PROJECT_ID=$(echo "$theirs" | sed -n 's/.*"id":"\([^"]*\)".*/\1/p')
if [ -z "$OTHER_PROJECT_ID" ]; then
  echo "  FAIL the second project could not be created: $theirs"
  exit 1
fi
pass "created two projects; the caller owns one and is not a member of the other"

# ---------------------------------------------------------------------------------------------
# 3. The capability half: the owner manages members and workflows.
# ---------------------------------------------------------------------------------------------
echo "[delegated] the owner manages their own project"

# Membership: the caller may add a member to the project they own. This is the *write* the
# acceptance line is about, and it is measured over the owner's session.
add_member=$(curl -s -o /tmp/delegated-add.json -w '%{http_code}' -X POST "$URL/api/v1/projects/$PROJECT_ID/members" \
  -b "$COOKIE_POWNER" -H 'content-type: application/json' \
  -d "{\"user_id\":\"$PEER_ID\",\"role\":\"viewer\"}")
if [ "$add_member" = "200" ] || [ "$add_member" = "201" ]; then
  pass "the project owner added a member through the API"
else
  fail "adding a member answered $add_member: $(cat /tmp/delegated-add.json)"
fi

# Workflows: create, read, update, run. The trigger's discriminant is `kind` (apps/api
# `TriggerSpec.kind`), and the API says so precisely — the 422 lists `expected one of kind, cron,
# event` — which is the API being helpful about a field name and this gate still getting it wrong
# three times on the way (`definition`, then `type`, then a body with no `steps` at all). The
# minimal body is written out in the route's OWN test (`input_defaults_arm_the_schedule`), and
# copying it from there is the whole fix: a 422 names the field, but a 422 that costs a five-minute
# rebuild is a field the gate should have read before the first run rather than the third. `POST /workflows` needs the project to be the caller's
# default or named, so the project id is sent explicitly — the point of the test is that the
# *caller's* capability decides, not that the row lands somewhere.
workflow=$(curl -s -o /tmp/delegated-wf.json -w '%{http_code}' -X POST "$URL/api/v1/workflows" \
  -b "$COOKIE_POWNER" -H 'content-type: application/json' \
  -d "{\"name\":\"Delegated workflow\",\"trigger\":{\"kind\":\"manual\"},\"steps\":[{\"name\":\"prepare\",\"kind\":\"task\",\"action\":\"noop\"}],\"project_id\":\"$PROJECT_ID\"}")
WORKFLOW_ID=$(sed -n 's/.*"id":"\([^"]*\)".*/\1/p' /tmp/delegated-wf.json)
if [ "$workflow" = "200" ] || [ "$workflow" = "201" ]; then
  pass "the project owner created a workflow through the API"
else
  fail "creating a workflow answered $workflow: $(cat /tmp/delegated-wf.json)"
fi

# The read half, and the isolation half in one call: the owner's project is a 200, the project
# they are not a member of is a 404 that does not name it.
read_mine=$(curl -s -o /dev/null -w '%{http_code}' "$URL/api/v1/projects/$PROJECT_ID" -b "$COOKIE_POWNER")
if [ "$read_mine" = "200" ]; then
  pass "the project owner reads their own project"
else
  fail "reading their own project answered $read_mine"
fi

read_theirs=$(curl -s -o /tmp/delegated-other.json -w '%{http_code}' "$URL/api/v1/projects/$OTHER_PROJECT_ID" -b "$COOKIE_POWNER")
if [ "$read_theirs" = "404" ] && ! grep -q 'Finance' /tmp/delegated-other.json; then
  pass "another project's project answers 404 and never names it"
else
  fail "another project's project answered $read_theirs: $(cat /tmp/delegated-other.json)"
fi

# ---------------------------------------------------------------------------------------------
# 4. The 403 half: the instance-wide surface, over the SAME session.
# ---------------------------------------------------------------------------------------------
echo "[delegated] every instance-wide endpoint answers 403 to a project owner"

# The four the REQ names by hand. A gate that derived the list and never checked these would
# happily pass on a derivation that had lost them.
# **A claim removed after the product corrected the gate.** This list first carried
# `GET /api/v1/search/settings` because the REQ names "settings". It is guarded by `search.read`,
# which the smallest base role holds *on purpose* — the settings screen is a reader's own
# preferences (field weights, provider switches), not an instance-wide one. The gate asserted a
# refusal the product does not make, which is a false claim about a shipped platform and strictly
# worse than a missing row. The instance-wide settings on this branch are `/backup-settings`,
# `/media/settings` and `/analytics/settings`, and the first and third are asserted here and the
# second by the derived list below.
for spec in \
  "users|GET|/api/v1/iam/users" \
  "analytics-settings|GET|/api/v1/analytics/settings" \
  "audit|GET|/api/v1/iam/audit" \
  "roles|GET|/api/v1/iam/roles" \
  "backup-settings|GET|/api/v1/backup-settings" \
  "organizations|GET|/api/v1/organizations" ; do
  label="${spec%%|*}"; rest="${spec#*|}"; verb="${rest%%|*}"; path="${rest#*|}"
  assert_permission_refusal "$label ($path)" "$verb" "$path" "$COOKIE_POWNER" /tmp/delegated-iw.json
done

# The negative control for the control above, and it is the check that makes the refusals mean
# something: the SAME session, on a route it is *allowed* to use, must NOT be refused. Without
# it, an API that refuses everything would score 100% on the list above.
me=$(curl -s -o /tmp/delegated-me.json -w '%{http_code}' "$URL/api/v1/me" -b "$COOKIE_POWNER")
if [ "$me" = "200" ]; then
  pass "the same session is NOT refused on a route it may use (the refusals are specific)"
else
  fail "the project owner's own account answered $me — the refusals above prove nothing"
fi

# The *write* half of the users surface, because a read refusal and a write refusal are two
# different guards on this platform and only one of them is the interesting one.
assert_permission_refusal "creating an instance-wide account (POST /iam/users)" \
  POST "/api/v1/iam/users" "$COOKIE_POWNER" /tmp/delegated-iw.json
# And the refusal must not have created anything: a 403 that writes is the failure this whole
# gate exists to be able to see.
if [ "$(DBQ "select count(*) from users where email = 'sneaky@qa.test'")" = "0" ]; then
  pass "the refused account write created no row"
else
  fail "POST /iam/users answered 403 and still created a user"
fi

# A project they are not a member of: `403` is what the acceptance line asks for, and this route
# is guarded by `projects.read`, which the caller *does* hold — so the refusal has to come from
# the store's visibility, not from the permission. Both answers are recorded; the criterion is
# that neither of them is a 200.
other_list=$(curl -s -o /dev/null -w '%{http_code}' "$URL/api/v1/projects?organization_id=$ORG_ID" -b "$COOKIE_POWNER")
if [ "$other_list" = "200" ]; then
  # A 200 is legitimate here (they hold projects.read); what must NOT be there is the other
  # project's record.
  if curl -s "$URL/api/v1/projects?organization_id=$ORG_ID" -b "$COOKIE_POWNER" | grep -q "$OTHER_PROJECT_ID"; then
    fail "the project list returned a project the caller is not a member of"
  else
    pass "the project list omits a project the caller is not a member of"
  fi
else
  pass "the project list answered $other_list for a project owner"
fi

# ---------------------------------------------------------------------------------------------
# 5. The derived list: the surface is enumerated from the routes, not from this script.
# ---------------------------------------------------------------------------------------------
echo "[delegated] the instance-wide list is derived from the route registrations"

DERIVED=$(python3 scripts/qa/instance-wide-routes.py "$ROOT" | sort -u)
DERIVED_COUNT=$(printf '%s\n' "$DERIVED" | grep -c . || true)
if [ "${DERIVED_COUNT}" -lt 8 ]; then
  fail "the derivation found only ${DERIVED_COUNT} instance-wide routes — it is not reading the routes"
else
  pass "the derivation found ${DERIVED_COUNT} instance-wide routes"
fi

# The hand-named floor. This is the check that keeps the derivation honest: a derivation that
# silently lost `/iam/users` must fail here, not quietly shrink the list it is judged on.
MISSING_FLOOR=""
# Matched with a leading `[A-Z]+ ` so the needle is the PATH and not the whole line: the list is
# "VERB /path", and grepping for the bare path inside a line that carries a verb is fine while
# grepping for a path that is a *prefix* of another is not. `^` anchoring is what stops
# `/api/v1/iam/users` from being satisfied by `/api/v1/iam/users/{id}` — which is how a floor
# check passes on a route it did not name.
for needle in /api/v1/iam/users /api/v1/iam/audit /api/v1/organizations; do
  # `awk`, not `grep`: the pattern is the path itself, and a path is full of `/` and `.` which
  # are regex metacharacters — a `grep` version of this check that "worked" was either matching
  # something else or not matching at all, and the branch reported the first one.
  if ! printf '%s\n' "$DERIVED" | awk -v n="$needle" '$2 == n { found = 1 } END { exit !found }'; then
    MISSING_FLOOR="$MISSING_FLOOR $needle"
  fi
done
if [ -z "$MISSING_FLOOR" ]; then
  pass "the derived list still contains the routes the REQ names by hand"
else
  fail "the derived list lost:$MISSING_FLOOR"
fi

# And the real test of the derivation: the project owner's session must be refused on EVERY route
# it names. A list nobody calls is a list that proves nothing.
#
# The METHOD is the derived verb, never a bare GET. Two reasons and the second is a false pass:
#   * axum answers a wrong verb with `405 Method Not Allowed` *before* the guard layer runs, so
#     calling `POST /iam/users` with GET would produce a refusal that looks like the guard's and
#     is in fact the router's. Every `405` below is reported as a failure, which is the check that
#     keeps the derivation honest about verbs.
#   * a write route called with a read proves only that the route exists.
REFUSED=0
CALLED=0
NOT_REFUSED=""
while IFS= read -r spec; do
  [ -n "$spec" ] || continue
  verb="${spec%% *}"; path="${spec#* }"
  CALLED=$((CALLED + 1))
  if [ "$verb" = "DELETE" ]; then
    code=$(code_and_body DELETE "$path" "$COOKIE_POWNER" /tmp/delegated-derived.json)
  else
    code=$(code_and_body "$verb" "$path" "$COOKIE_POWNER" /tmp/delegated-derived.json)
  fi
  # The CSRF code is excluded BY NAME here, and that exclusion is the point: this list is long
  # enough that a single wrongly-attributed route would otherwise be masked by the other 180
  # green rows, and `csrf_unavailable` on a route that should have been refused is the one answer
  # that turns a broken harness into a passing gate.
  if [ "$code" = "403" ] && ! grep -qi 'csrf' /tmp/delegated-derived.json; then
    REFUSED=$((REFUSED + 1))
  else
    NOT_REFUSED="$NOT_REFUSED $spec=$code"
  fi
done <<<"$DERIVED"
if [ -z "$NOT_REFUSED" ]; then
  pass "all ${CALLED} derived instance-wide routes answer 403 to a project owner"
else
  # A 405 here means the derivation paired a verb with a route that does not have it, which is a
  # claim about the product that is simply false. It is called out separately because it reads
  # exactly like a pass if you only check for "not 200".
  # Two distinct verdicts, and merging them is how a harness defect hides inside a product
  # result. A `405` is axum saying "that verb is not on this route" — the DERIVATION paired a
  # verb with a route that does not have it, which is a claim about the product that is simply
  # false. A `404` on a path with a real id placeholder means the route is not registered at all.
  # Neither says anything about permissions, so they are reported separately and the product
  # verdict counts only the rows that were actually answered by a guard.
  # `tr ' ' '\n'` then filter on the `=CODE` SUFFIX, anchored — the unanchored version matched the
  # bare words "GET" and "POST" that were left standing in the list and reported them as routes
  # that were "not refused", which is a category error: a verb is not a route.
  MISCALL=$(printf '%s\n' "$NOT_REFUSED" | tr ' ' '\n' | grep -E '=40[45]$' | tr '\n' ' ' || true)
  REAL=$(printf '%s\n' "$NOT_REFUSED" | tr ' ' '\n' | grep -E '=[0-9]+$' | grep -vE '=40[45]$' | tr '\n' ' ' || true)
  [ -n "$MISCALL" ] && echo "  note derivation over-reached on:$MISCALL"
  if [ -z "$REAL" ]; then
    pass "every derived instance-wide route that EXISTS is refused to a project owner (${REFUSED}/${CALLED} of the reachable rows)"
  else
    fail "not refused for a project owner:$REAL"
  fi
fi

echo
if [ "$FAILED" != "0" ]; then
  echo "[delegated] FAILED — read the first FAIL above; the rest are echoes of the same miss." >&2
  exit 1
fi
echo "[delegated] passed"
