//! `/api/v1/app-builder/…` — the plan console and the review workspace
//! (docs/requests/REQ-045, slice 2).
//!
//! Slice 1 wrote the store and the validators as **library functions**. Nothing on the wire
//! could reach them, so a plan could be generated by nothing and reviewed by nobody — the
//! module existed and the feature did not. This file is the wire, and it is deliberately the
//! *second half* of the request rather than the whole of it: generation streams (slice 1's
//! artifacts through `POST /generate`), review happens here, and **apply does not exist
//! yet**. `POST /plans/{id}/apply` is not registered and not faked — a button that answers
//! "coming soon" is exactly what the plan's Definition of Done forbids, and the `409` a
//! reviewer gets instead comes from the blockers list with every unresolved artifact named.
//!
//! Four decisions, each of which could have gone the other way:
//!
//! * **Tenancy is the store's `where`, never a check afterwards.** A plan of another tenant is
//!   *absent*, so a direct fetch answers `404` and a list answers empty. A handler that
//!     refused it with `403` would tell the caller which ids exist somewhere.
//! * **A rejected artifact requires a reason, and an accepted one may not be re-rejected in
//!   silence.** `reject_artifact` refuses an empty reason (slice 1's store rule), which is why
//!   this file has no code path that could write one.
//! * **Accept is refused for an artifact the validator refused — by name.** The store already
//!   enforces it, and the handler maps that refusal to `422` with the *first finding* in the
//!   body, because the review screen renders it as the two buttons that could help rather
//!   than as a toast.
//! * **The vocabulary endpoints are free of a database round-trip.** The sample prompts and
//!   the kind list are what the landing page shows *before* it knows whether a provider is
//!   connected, and the no-provider state is one of the three things the empty state has to
//!   be able to say.

use std::convert::Infallible;

use axum::Json;
use axum::extract::{Path, Query, State};
use axum::http::StatusCode;
use axum::response::Response;
use axum::response::sse::{Event, KeepAlive, Sse};
use omnion_ai_hub::resolve;
use omnion_audit::NewAuditEntry;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use time::OffsetDateTime;
use tokio::sync::mpsc;
use tokio_stream::StreamExt;
use tokio_stream::wrappers::ReceiverStream;
use uuid::Uuid;

use crate::auth::CurrentSession;
use crate::client_ip::ClientAddress;
use crate::error::ApiError;
use crate::scope::ensure_same_organization;
use crate::state::AppState;

use omnion_module_app_builder as builder;

/// How many stage frames may queue in front of a client before the stream waits for it.
pub(crate) const STREAM_BUFFER: usize = 8;

/// Rows a page of the console list returns when the caller does not ask for a size.
const LIST_PAGE_DEFAULT: i64 = 20;

/// Most rows a page returns.
const LIST_PAGE_MAX: i64 = 100;

/// Most plans one bulk delete may carry.
///
/// The console selects a page (20 rows by default), so the bound is generous rather than
/// tight: it exists to stop a request that would hold the table's worth of ids in one
/// statement, not to shape the interface. `media.manage`'s bulk bar uses the same number.
const MAX_BULK_SELECTION: usize = 100;

/// The three sample prompts the landing page offers, exactly as the request names them.
const EXAMPLES: &[(&str, &str)] = &[
    (
        "Create an app to manage employees' leave requests",
        "Create an app to manage employees' leave requests",
    ),
    (
        "Personel izin taleplerini yönetmek için bir uygulama oluştur",
        "Personel izin taleplerini yönetmek için bir uygulama oluştur",
    ),
    (
        "Track supplier contracts with renewal reminders",
        "Track supplier contracts with renewal reminders",
    ),
];

// ---------------------------------------------------------------------------------------------
// Response bodies
// ---------------------------------------------------------------------------------------------

/// One plan as the console list renders it.
///
/// The counts ride **this** row rather than being fetched per plan: the list re-fetches on
/// every filter change, and a count per row turns one query into eleven whose answers can
/// disagree with the page they decorate.
#[derive(Debug, Serialize)]
pub struct PlanSummary {
    /// Plan identity.
    pub id: Uuid,
    /// Title, which is the prompt's own first clause until the model names it.
    pub title: String,
    /// Lifecycle state.
    pub status: String,
    /// Which attempt within a chain.
    pub plan_version: i32,
    /// The frozen model.
    pub model_label: String,
    /// Who asked.
    pub created_by: Option<Uuid>,
    /// Artifacts of every kind.
    pub artifact_count: i64,
    /// Artifacts the reviewer resolved.
    pub accepted_count: i64,
    /// Artifacts the reviewer refused or a regeneration retired.
    pub rejected_count: i64,
    /// Artifacts still waiting.
    pub pending_count: i64,
    /// Artifacts the validator refused.
    pub invalid_count: i64,
    /// What it cost in cents.
    pub cost_cents: i32,
    /// Why generation failed or the plan was rejected.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Row creation.
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: OffsetDateTime,
}

impl PlanSummary {
    fn build(plan: &builder::AppBuilderPlan, counts: &builder::PlanCounts) -> Self {
        Self {
            id: plan.id,
            title: plan.title.clone(),
            status: plan.status.clone(),
            plan_version: plan.plan_version,
            model_label: plan.model_label.clone(),
            created_by: plan.created_by,
            artifact_count: counts.artifacts,
            accepted_count: counts.accepted,
            rejected_count: counts.rejected,
            pending_count: counts.pending,
            invalid_count: counts.invalid,
            cost_cents: plan.cost_cents,
            error: plan.error.clone(),
            created_at: plan.created_at,
        }
    }
}

/// The list, plus what the filter bar draws itself from.
#[derive(Debug, Serialize)]
pub struct PlanListBody {
    /// The page's rows.
    pub plans: Vec<PlanSummary>,
    /// How many rows match the filter, ignoring the page window.
    pub total: i64,
    /// Every status a plan may hold, for the filter's select.
    pub statuses: Vec<&'static str>,
    /// How many rows a page holds by default.
    pub page_size: i64,
}

/// One artifact as the review tree and the detail pane render it.
#[derive(Debug, Serialize)]
pub struct ArtifactBody {
    /// Artifact identity.
    pub id: Uuid,
    /// Which kind.
    pub kind: String,
    /// Stable key within (plan, kind).
    pub key: String,
    /// The artifact this one hangs off.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent_key: Option<String>,
    /// Order in the tree.
    pub ordinal: i32,
    /// Where the reviewer has got to.
    pub status: String,
    /// The artifact itself.
    pub spec: Value,
    /// The model's own explanation.
    pub rationale: String,
    /// What the validator said, `{ path, message }` each.
    pub validation: Value,
    /// Why the reviewer refused it.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub rejected_reason: Option<String>,
    /// The version this one replaced.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub supersedes_id: Option<Uuid>,
    /// Last write.
    #[serde(with = "time::serde::rfc3339")]
    pub updated_at: OffsetDateTime,
}

impl ArtifactBody {
    fn build(artifact: &builder::AppBuilderArtifact) -> Self {
        Self {
            id: artifact.id,
            kind: artifact.kind.clone(),
            key: artifact.key.clone(),
            parent_key: artifact.parent_key.clone(),
            ordinal: artifact.ordinal,
            status: artifact.status.clone(),
            spec: artifact.spec.clone(),
            rationale: artifact.rationale.clone(),
            validation: artifact.validation.clone(),
            rejected_reason: artifact.rejected_reason.clone(),
            supersedes_id: artifact.supersedes_id,
            updated_at: artifact.updated_at,
        }
    }
}

/// One plan with everything the review screen draws.
#[derive(Debug, Serialize)]
pub struct PlanBody {
    /// The plan itself.
    pub plan: PlanSummary,
    /// Its artifacts, ordered the way the tree groups them.
    pub artifacts: Vec<ArtifactBody>,
    /// The counters the footer renders.
    pub counts: builder::PlanCounts,
    /// What stands between the plan and apply, named.
    ///
    /// **Not derived by the client.** The blockers are a property of the plan's whole set —
    /// including a required kind no artifact row could express — so a client that re-derived
    /// the rule would have to re-implement it and would eventually disagree with apply.
    pub blockers: Vec<BlockedBody>,
    /// Whether every required artifact is resolved, i.e. whether the Apply button may be offered.
    pub applicable: bool,
    /// Why the whole plan was rejected or generation failed.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub decision_reason: Option<String>,
    /// When apply finished, `null` until then.
    #[serde(with = "time::serde::rfc3339::option")]
    pub applied_at: Option<OffsetDateTime>,
}

/// One blocker, as the footer's summary list renders it.
#[derive(Debug, Serialize)]
pub struct BlockedBody {
    /// Which kind.
    pub kind: String,
    /// Its key, empty when the plan never proposed that kind at all.
    pub key: String,
    /// Why it blocks: `rejected`, `invalid`, `pending` or `missing`.
    pub status: String,
    /// The first finding or the reviewer's reason.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

/// What the landing page shows before it knows whether a provider is connected.
#[derive(Debug, Serialize)]
pub struct VocabularyBody {
    /// The click-to-fill sample prompts.
    pub examples: Vec<ExampleBody>,
    /// Every artifact kind, in the order the tree groups them.
    pub kinds: Vec<&'static str>,
    /// Every artifact status.
    pub statuses: Vec<&'static str>,
    /// Every plan status, for the filter.
    pub plan_statuses: Vec<&'static str>,
    /// The field types a generated entity may declare.
    pub field_types: Vec<&'static str>,
    /// The longest a prompt may be.
    pub max_prompt_len: usize,
}

/// One worked example.
#[derive(Debug, Serialize)]
pub struct ExampleBody {
    /// The chip's label.
    pub title: &'static str,
    /// The prompt to fill the composer with.
    pub prompt: &'static str,
}

/// What an accept, reject or edit answers.
#[derive(Debug, Serialize)]
pub struct ArtifactDecisionBody {
    /// The artifact as it now reads, so the client never re-fetches to draw the new state.
    pub artifact: ArtifactBody,
    /// The plan's counters, so the footer moves without a second round trip.
    pub counts: builder::PlanCounts,
    /// The blockers after the decision, because accepting one artifact usually removes one.
    pub blockers: Vec<BlockedBody>,
}

/// What rejecting or deleting a plan answers.
#[derive(Debug, Serialize)]
pub struct PlanDecisionBody {
    /// The plan as it now reads.
    pub plan: PlanSummary,
}

// ---------------------------------------------------------------------------------------------
// Request bodies
// ---------------------------------------------------------------------------------------------

/// What the console list asks for. Every field is optional and every field is in the URL, so
/// a reload and the QA walkthrough land on the same view.
#[derive(Debug, Default, Deserialize)]
pub struct PlanListQuery {
    /// Restrict to one status.
    pub status: Option<String>,
    /// Free text over title and prompt.
    pub q: Option<String>,
    /// "Mine only".
    pub mine: Option<bool>,
    /// Restrict to one author.
    pub by: Option<Uuid>,
    /// Organization, for a platform account.
    pub organization_id: Option<Uuid>,
    /// Rows to skip.
    pub offset: Option<i64>,
    /// Rows to return.
    pub limit: Option<i64>,
}

/// The generate form's body.
#[derive(Debug, Deserialize)]
pub struct GenerateBody {
    /// The operator's sentence.
    pub prompt: String,
    /// `provider/model`, or absent for the installation's default.
    pub model: Option<String>,
    /// A human's name for the plan; the model's wins when it sends one.
    pub title: Option<String>,
    /// Organization, for a platform account.
    pub organization_id: Option<Uuid>,
}

/// The edit form's body.
#[derive(Debug, Deserialize)]
pub struct EditArtifactBody {
    /// The artifact's new body. Anything the validator refuses lands as `invalid`, never as
    /// `edited`, so a review screen cannot render a broken artifact as "fixed".
    pub spec: Value,
}

/// The reject form's body.
#[derive(Debug, Deserialize)]
pub struct RejectBody {
    /// Why. Required by the store, and by the request: a bare rejection is a decision nobody
    /// can learn from.
    pub reason: String,
}

// ---------------------------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------------------------

/// `GET /api/v1/app-builder/plans` — one organization's plans.
pub async fn list_plans(
    State(state): State<AppState>,
    current: CurrentSession,
    Query(query): Query<PlanListQuery>,
) -> Result<Json<PlanListBody>, ApiError> {
    let organization_id = organization_of(&current, query.organization_id)?;
    let filter = builder::PlanFilter {
        status: query.status.clone(),
        text: query.q.clone(),
        // "Mine only" is resolved to the caller's own id **here** rather than accepted from the
        // URL: a `by=` parameter is how one account asks for another account's plans, and the
        // filter bar has no such control. `mine` is the control it has.
        created_by: if query.mine.unwrap_or(false) {
            Some(current.user.id)
        } else {
            query.by
        },
        offset: query.offset.unwrap_or_default().max(0),
        limit: query
            .limit
            .unwrap_or(LIST_PAGE_DEFAULT)
            .clamp(1, LIST_PAGE_MAX),
    };

    let page = builder::list_plans(state.db().pool(), Some(organization_id), &filter)
        .await
        // The filter is **caller input**, so a refusal here is a `422` about the request rather
        // than a `500` about the store. `store_error` would report an unknown `status` as a
        // server fault, which is both the wrong status and the wrong blame: the filter bar
        // sent a value the catalogue does not admit, and the answer belongs to whoever has to
        // fix it — the operator, who is told the vocabulary in the message.
        .map_err(validation_error)?;

    // The counts and the rows arrive in the same query, so they are zipped rather than looked
    // up: a plan without a matching count would be a store bug, and pairing by index is
    // exactly as safe as the query that produced them.
    let plans = page
        .plans
        .iter()
        .zip(page.counts.iter())
        .map(|(plan, counts)| PlanSummary::build(plan, counts))
        .collect();

    Ok(Json(PlanListBody {
        plans,
        total: page.total,
        statuses: builder::STATUSES.to_vec(),
        page_size: LIST_PAGE_DEFAULT,
    }))
}

/// `GET /api/v1/app-builder/plans/{id}` — one plan, for the review workspace.
pub async fn get_plan(
    State(state): State<AppState>,
    current: CurrentSession,
    Path(plan_id): Path<Uuid>,
) -> Result<Json<PlanBody>, ApiError> {
    let plan = plan_in_scope(&state, &current, plan_id).await?;
    let artifacts = builder::list_artifacts(state.db().pool(), plan.id)
        .await
        .map_err(store_error)?;
    let counts = builder::artifact_counts(state.db().pool(), plan.id)
        .await
        .map_err(store_error)?;
    let blockers = builder::blockers(state.db().pool(), plan.id)
        .await
        .map_err(store_error)?;
    let applicable = blockers.is_empty();

    Ok(Json(PlanBody {
        plan: PlanSummary::build(&plan, &counts),
        artifacts: artifacts.iter().map(ArtifactBody::build).collect(),
        counts,
        blockers: blockers.iter().map(BlockedBody::from).collect(),
        applicable,
        decision_reason: plan.decision_reason.clone(),
        applied_at: plan.applied_at,
    }))
}

/// `GET /api/v1/app-builder/examples` — the composer's vocabulary.
///
/// No database round-trip on purpose: this is the one endpoint the landing page loads **before**
/// it knows whether a provider is connected, and "no model is configured" is one of the three
/// states the empty state has to be able to say.
pub async fn examples() -> Result<Json<VocabularyBody>, ApiError> {
    Ok(Json(VocabularyBody {
        examples: EXAMPLES
            .iter()
            .map(|(title, prompt)| ExampleBody { title, prompt })
            .collect(),
        kinds: builder::KINDS.to_vec(),
        statuses: builder::ARTIFACT_STATUSES.to_vec(),
        plan_statuses: builder::STATUSES.to_vec(),
        field_types: builder::FIELD_TYPES.to_vec(),
        max_prompt_len: builder::MAX_PROMPT_LEN,
    }))
}

/// `PATCH /api/v1/app-builder/plans/{id}/artifacts/{artifact_id}` — edit a draft artifact.
///
/// The body a reviewer typed is **untrusted input of the same kind the model's is**, so it goes
/// through the same validator: an edit that breaks a key comes back `422` with the field path,
/// and an edit that merely has findings is stored as `invalid` rather than `edited`. A
/// validation that ran only on the way in would leave the screen showing "edited" above a body
/// the platform will refuse at apply.
pub async fn edit_artifact(
    State(state): State<AppState>,
    current: CurrentSession,
    address: ClientAddress,
    Path((plan_id, artifact_id)): Path<(Uuid, Uuid)>,
    Json(body): Json<EditArtifactBody>,
) -> Result<Json<ArtifactDecisionBody>, ApiError> {
    let plan = plan_in_scope(&state, &current, plan_id).await?;
    let artifact = artifact_of_plan(&state, &current, plan.id, artifact_id).await?;

    let draft = builder::NewArtifact {
        kind: artifact.kind.clone(),
        key: artifact.key.clone(),
        parent_key: artifact.parent_key.clone(),
        ordinal: artifact.ordinal,
        spec: body.spec.clone(),
        rationale: artifact.rationale.clone(),
        validation: Value::Null,
    };
    let findings = builder::validate_artifact(&draft);
    let edit = builder::EditedArtifact {
        spec: draft.spec.clone(),
        validation: serde_json::to_value(&findings).unwrap_or_else(|_| json!([])),
        supersedes_id: artifact.id,
    };

    let updated = builder::update_artifact_spec(state.db().pool(), artifact.id, &edit, &findings)
        .await
        .map_err(validation_error)?
        .ok_or_else(artifact_not_found)?;

    record(
        &state,
        NewAuditEntry::by_user(current.user.id, "app_builder.artifact.edited")
            .organization(plan.organization_id)
            .target("app_builder_artifact", artifact.id.to_string())
            .metadata(json!({
                "plan_id": plan.id,
                "kind": artifact.kind,
                "key": artifact.key,
                "findings": findings.len(),
            }))
            .ip_address(address.as_text()),
    )
    .await?;

    decision_body(&state, &plan, updated).await
}

/// `POST /api/v1/app-builder/plans/{id}/artifacts/{artifact_id}/accept` — accept an artifact.
///
/// The refusal that matters here is the store's: accepting an artifact the validator refused
/// is refused **by name, with the first finding and the two things a reviewer can do**, because
/// a `422` with no body is a dead end on a screen whose whole job is the next action.
pub async fn accept_artifact(
    State(state): State<AppState>,
    current: CurrentSession,
    address: ClientAddress,
    Path((plan_id, artifact_id)): Path<(Uuid, Uuid)>,
) -> Result<Json<ArtifactDecisionBody>, ApiError> {
    let plan = plan_in_scope(&state, &current, plan_id).await?;
    let artifact = artifact_of_plan(&state, &current, plan.id, artifact_id).await?;

    let updated = builder::accept_artifact(state.db().pool(), artifact.id)
        .await
        .map_err(validation_error)?
        .ok_or_else(artifact_not_found)?;

    record(
        &state,
        NewAuditEntry::by_user(current.user.id, "app_builder.artifact.accepted")
            .organization(plan.organization_id)
            .target("app_builder_artifact", artifact.id.to_string())
            .metadata(json!({ "plan_id": plan.id, "kind": artifact.kind, "key": artifact.key }))
            .ip_address(address.as_text()),
    )
    .await?;

    decision_body(&state, &plan, updated).await
}

/// `POST /api/v1/app-builder/plans/{id}/artifacts/{artifact_id}/reject` — refuse an artifact.
///
/// The reason is required here by the store, and that is the point: `POST` with an empty body
/// answers `400` naming the field rather than writing a rejection nobody can learn from.
pub async fn reject_artifact(
    State(state): State<AppState>,
    current: CurrentSession,
    address: ClientAddress,
    Path((plan_id, artifact_id)): Path<(Uuid, Uuid)>,
    Json(body): Json<RejectBody>,
) -> Result<Json<ArtifactDecisionBody>, ApiError> {
    let plan = plan_in_scope(&state, &current, plan_id).await?;
    let artifact = artifact_of_plan(&state, &current, plan.id, artifact_id).await?;

    let updated = builder::reject_artifact(state.db().pool(), artifact.id, &body.reason)
        .await
        .map_err(validation_error)?
        .ok_or_else(artifact_not_found)?;

    record(
        &state,
        NewAuditEntry::by_user(current.user.id, "app_builder.artifact.rejected")
            .organization(plan.organization_id)
            .target("app_builder_artifact", artifact.id.to_string())
            .metadata(json!({
                "plan_id": plan.id,
                "kind": artifact.kind,
                "key": artifact.key,
                "reason": body.reason,
            }))
            .ip_address(address.as_text()),
    )
    .await?;

    decision_body(&state, &plan, updated).await
}

/// `POST /api/v1/app-builder/plans/{id}/artifacts/{artifact_id}/regenerate` — one artifact again,
/// with a note.
///
/// Two rows and one status change, in one transaction, in the store: the previous version is
/// retired as `rejected` with `superseded by a regenerated version` rather than deleted,
/// because the request asks for kept versions so a rejected attempt stays comparable.
pub async fn regenerate_artifact(
    State(state): State<AppState>,
    current: CurrentSession,
    address: ClientAddress,
    Path((plan_id, artifact_id)): Path<(Uuid, Uuid)>,
    Json(body): Json<RegenerateBody>,
) -> Result<Json<ArtifactDecisionBody>, ApiError> {
    let plan = plan_in_scope(&state, &current, plan_id).await?;
    let artifact = artifact_of_plan(&state, &current, plan.id, artifact_id).await?;

    // Resolution happens before anything is written, so "no provider is connected" is a `409`
    // the landing page renders rather than a half-regenerated tree.
    let resolved = resolve(state.db().pool(), body.model.as_deref())
        .await
        .map_err(provider_error)?;

    let feedback = body.feedback.trim();
    if feedback.is_empty() {
        return Err(ApiError::bad_request(
            "feedback_required",
            "say what should change — a regeneration with no note is a second guess",
        ));
    }

    // The prompt the model is re-asked: the artifact as it stands, plus what the reviewer
    // said about it. Carrying the previous body is what makes this a revision rather than a
    // reroll; the store's own shape (`supersedes_id`) is what makes the old one comparable.
    let prompt = format!(
        "Revise one artifact of an app plan.\n\n\
         The request the plan answers:\n{}\n\n\
         The artifact as it stands (kind `{}`, key `{}`):\n{}\n\n\
         The reviewer's note:\n{}\n\n\
         Answer with the revised artifact as JSON.",
        plan.prompt,
        artifact.kind,
        artifact.key,
        serde_json::to_string_pretty(&artifact.spec).unwrap_or_else(|_| "{}".to_owned()),
        feedback
    );

    let replacement = run_generation(&resolved, &prompt).await?;

    let candidate = builder::NewArtifact {
        kind: artifact.kind.clone(),
        key: artifact.key.clone(),
        parent_key: artifact.parent_key.clone(),
        ordinal: artifact.ordinal,
        spec: replacement.artifact.clone(),
        rationale: replacement.rationale.clone(),
        validation: Value::Null,
    };
    let findings = builder::validate_artifact(&candidate);
    let updated =
        builder::supersede_artifact(state.db().pool(), artifact.id, &candidate, &findings)
            .await
            .map_err(validation_error)?
            .ok_or_else(|| {
                ApiError::new(
                    StatusCode::CONFLICT,
                    "artifact_already_accepted",
                    format!(
                        "`{}` is accepted; accept a regeneration by regenerating before you accept \
                     the previous version",
                        artifact.key
                    ),
                )
            })?;

    record(
        &state,
        NewAuditEntry::by_user(current.user.id, "app_builder.artifact.regenerated")
            .organization(plan.organization_id)
            .target("app_builder_artifact", artifact.id.to_string())
            .metadata(json!({
                "plan_id": plan.id,
                "kind": artifact.kind,
                "key": artifact.key,
                "feedback": feedback,
                "model": replacement.model_label,
                "tokens": replacement.tokens,
            }))
            .ip_address(address.as_text()),
    )
    .await?;

    decision_body(&state, &plan, updated).await
}

/// The regenerate form's body.
#[derive(Debug, Deserialize)]
pub struct RegenerateBody {
    /// What should change. Required, and checked here rather than only in the store so the
    /// empty case is a `400` about the field rather than a wasted generation.
    pub feedback: String,
    /// `provider/model`, or absent for the installation's default.
    pub model: Option<String>,
}

/// `POST /api/v1/app-builder/plans/{id}/reject` — refuse the whole plan.
pub async fn reject_plan(
    State(state): State<AppState>,
    current: CurrentSession,
    address: ClientAddress,
    Path(plan_id): Path<Uuid>,
    Json(body): Json<RejectBody>,
) -> Result<Json<PlanDecisionBody>, ApiError> {
    let plan = plan_in_scope(&state, &current, plan_id).await?;

    let rejected = builder::reject_plan(state.db().pool(), plan.id, &body.reason)
        .await
        .map_err(validation_error)?
        .ok_or_else(|| {
            // The store's `where` admits only open plans, so this is a plan that is already
            // applied, rejected or being applied. Naming its status is the whole message: the
            // operator's next move differs for each.
            ApiError::new(
                StatusCode::CONFLICT,
                "plan_not_open",
                format!("this plan is `{}`, not an open plan", plan.status),
            )
        })?;

    record(
        &state,
        NewAuditEntry::by_user(current.user.id, "app_builder.plan.rejected")
            .organization(plan.organization_id)
            .target("app_builder_plan", plan.id.to_string())
            .metadata(json!({ "reason": body.reason, "title": plan.title }))
            .ip_address(address.as_text()),
    )
    .await?;

    let counts = builder::artifact_counts(state.db().pool(), plan.id)
        .await
        .map_err(store_error)?;
    Ok(Json(PlanDecisionBody {
        plan: PlanSummary::build(&rejected, &counts),
    }))
}

/// `DELETE /api/v1/app-builder/plans/{id}` — remove a plan that was never applied.
///
/// The store refuses an applied plan and returns "no row" rather than a reason, so the handler
/// distinguishes the two cases: a plan that is not there is a `404`, and a plan that is there
/// but applied is a `409` that names the fact. Collapsing them would answer `404` for a plan
/// the operator can see in the list, which is the one answer that helps nobody.
pub async fn delete_plan(
    State(state): State<AppState>,
    current: CurrentSession,
    address: ClientAddress,
    Path(plan_id): Path<Uuid>,
) -> Result<StatusCode, ApiError> {
    let plan = plan_in_scope(&state, &current, plan_id).await?;

    let deleted = builder::delete_plan(state.db().pool(), plan.id)
        .await
        .map_err(store_error)?;
    if !deleted {
        return Err(ApiError::new(
            StatusCode::CONFLICT,
            "plan_applied",
            "this plan was applied, and an applied plan's artifacts are what the live app was \
             built from — reject it instead of deleting it",
        ));
    }

    record(
        &state,
        NewAuditEntry::by_user(current.user.id, "app_builder.plan.deleted")
            .organization(plan.organization_id)
            .target("app_builder_plan", plan.id.to_string())
            .metadata(json!({ "title": plan.title, "status": plan.status }))
            .ip_address(address.as_text()),
    )
    .await?;

    Ok(StatusCode::NO_CONTENT)
}

/// What a bulk delete asks for.
#[derive(Debug, Deserialize)]
pub struct BulkDeleteBody {
    /// The plans to remove. An applied one is refused by name rather than deleted.
    pub ids: Vec<Uuid>,
}

/// One plan a bulk delete would not remove.
#[derive(Debug, Serialize)]
pub struct BulkDeleteFailure {
    /// The plan the caller named.
    pub id: Uuid,
    /// Why it is still there.
    pub message: String,
}

/// The answer to a bulk delete: what went, and what stayed.
///
/// **Both halves, always.** A response carrying only `deleted` renders a partial bulk as a
/// complete one — the operator's next action is to trust the count, and an applied plan that
/// silently survived would leave them believing the console is empty when it is not.
#[derive(Debug, Serialize)]
pub struct BulkDeleteAnswer {
    /// How many plans the request named.
    pub requested: usize,
    /// How many are gone.
    pub deleted: usize,
    /// The plans that are still there, each with the reason.
    pub failures: Vec<BulkDeleteFailure>,
}

/// `POST /api/v1/app-builder/plans/bulk-delete` — remove a selection of drafts.
///
/// **Three decisions, each of which had a cheaper alternative that would have been wrong.**
///
/// 1. **The answer is `200` with per-plan failures, not `204` and not `409`.** "Two of five
///    deleted, one was applied" is the truth of the call, and a status code can only say
///    whether *anything* went. The console's confirmation already names how many drafts are
///    about to go, so it can render the outcome in the same shape it asked in.
/// 2. **The selection is resolved inside the caller's organization before anything is
///    written.** `delete_plans` reads the rows with the tenant predicate and hands only what
///    is left to the `delete`, because the ids are the caller's — nothing inside a `delete`
///    looks at an organization, so a handler that passed the array straight through would be
///    deleting other tenants' plans and calling it a 200.
/// 3. **`appbuilder.review`, the same key the single delete carries.** A bulk is not a lesser
///    power; it is the same power over several rows at once, and guarding it differently would
///    mean the least-privileged reviewer could delete a page of drafts one row at a time but
///    not in bulk — which is a rule nobody would write on purpose.
///
/// An empty `ids` is refused rather than answered as "nothing to do": a button that reports
/// success for an empty selection is a button that cannot be distinguished from one that was
/// never wired.
pub async fn bulk_delete_plans(
    State(state): State<AppState>,
    current: CurrentSession,
    address: ClientAddress,
    Json(body): Json<BulkDeleteBody>,
) -> Result<Json<BulkDeleteAnswer>, ApiError> {
    if body.ids.is_empty() {
        return Err(ApiError::bad_request(
            "selection_required",
            "name the plans to delete — an empty selection deletes nothing and reports nothing",
        ));
    }
    if body.ids.len() > MAX_BULK_SELECTION {
        return Err(ApiError::bad_request(
            "selection_too_large",
            format!(
                "a bulk delete carries at most {MAX_BULK_SELECTION} plans; \
                 the console selects one page at a time"
            ),
        ));
    }

    // Same tenancy resolution as every other route here: a platform account must name the
    // tenant, and a scoped account gets its own.
    let organization_id = organization_of(&current, None)?;

    let report = builder::delete_plans(state.db().pool(), &body.ids, Some(organization_id))
        .await
        .map_err(store_error)?;

    record(
        &state,
        NewAuditEntry::by_user(current.user.id, "app_builder.plan.bulk_deleted")
            .organization(Some(organization_id))
            .target(
                "app_builder_plan",
                format!("{} plans", report.deleted.len()),
            )
            .metadata(json!({
                "requested": report.requested(),
                "deleted": report.deleted.len(),
                "failed": report.failures.len(),
            }))
            .ip_address(address.as_text()),
    )
    .await?;

    Ok(Json(BulkDeleteAnswer {
        requested: report.requested(),
        deleted: report.deleted.len(),
        failures: report
            .failures
            .into_iter()
            .map(|refused| BulkDeleteFailure {
                id: refused.id,
                message: refused.message,
            })
            .collect(),
    }))
}

/// `GET /api/v1/app-builder/plans/{id}/export` — the plan as a JSON file.
///
/// **A download, not a JSON body.** The console's bulk bar offers "Export plan JSON" next to
/// the delete, and an endpoint that answers `application/json` inline makes the browser open
/// a tab the operator then has to save by hand. `Content-Disposition: attachment` is what
/// turns "the request succeeded" into "a file arrived", and it is why this returns a raw
/// `Response` rather than `Json<PlanExport>`.
///
/// **Three decisions, each of which could have produced a file that lies.**
///
/// 1. **The document is built from the four reads the review screen already makes** — plan,
///    artifacts, counts, blockers — rather than from a narrower query written for the
///    export. An export assembled from *different* reads is a second view of the same plan
///    that can disagree with the first, and a reviewer comparing a file against the screen
///    would be comparing a real inconsistency the platform introduced.
/// 2. **The plan's tenant is resolved before a single row is read**, through the same
///    `plan_in_scope` every other route uses. An export that read first and checked after
///    would have written another tenant's plan to a download before refusing.
/// 3. **`appbuilder.read` is the permission, not `appbuilder.review`.** Exporting is
///    reading: a reviewer who may not change anything must still be able to take a plan
///    away, or "review, then hand the file on" is impossible for the least-privileged
///    account that is meant to exist. The audit row names the account either way.
///
/// The filename comes from the plan's short id, never its title — the title is free text
/// and free text inside a response header is a header-injection vector (see
/// `builder::export_filename`).
pub async fn export_plan(
    State(state): State<AppState>,
    current: CurrentSession,
    address: ClientAddress,
    Path(plan_id): Path<Uuid>,
) -> Result<Response, ApiError> {
    let plan = plan_in_scope(&state, &current, plan_id).await?;

    let artifacts = builder::list_artifacts(state.db().pool(), plan.id)
        .await
        .map_err(store_error)?;
    let counts = builder::artifact_counts(state.db().pool(), plan.id)
        .await
        .map_err(store_error)?;
    let blockers = builder::blockers(state.db().pool(), plan.id)
        .await
        .map_err(store_error)?;

    let body = builder::render_plan_export(&builder::build_plan_export(
        &plan, &artifacts, counts, &blockers,
    ))
    .map_err(store_error)?;
    let filename = builder::export_filename(&plan);

    // Read-only by name, and `no-store` so a second export of the same plan after a review
    // is not answered from the browser's cache: an export is a snapshot of a moment, and a
    // cached one is a snapshot of a moment somebody has since moved on from.
    let headers = [
        (
            axum::http::header::CONTENT_TYPE,
            "application/json; charset=utf-8".to_owned(),
        ),
        (
            axum::http::header::CONTENT_DISPOSITION,
            format!("attachment; filename=\"{filename}\""),
        ),
        (axum::http::header::CACHE_CONTROL, "no-store".to_owned()),
    ];

    let mut response = Response::new(axum::body::Body::from(body));
    for (name, value) in headers {
        if let Ok(value) = axum::http::HeaderValue::from_str(&value) {
            response.headers_mut().insert(name, value);
        }
    }

    record(
        &state,
        NewAuditEntry::by_user(current.user.id, "app_builder.plan.exported")
            .organization(plan.organization_id)
            .target("app_builder_plan", plan.id.to_string())
            .metadata(json!({ "artifacts": artifacts.len(), "filename": filename }))
            .ip_address(address.as_text()),
    )
    .await?;

    Ok(response)
}

/// `POST /api/v1/app-builder/generate` — a prompt becomes a plan, streamed.
///
/// **The typed generator, which until this slice did not exist.** The route was registered
/// and answered with a failure that named its own absence ("the typed artifact generator is
/// not wired yet"), which is the same defect as a button that says "coming soon" wearing a
/// status code: a reviewer pressed Generate, saw an error, and had learned nothing about
/// their application. Now the provider is asked once with the platform's own schema prompt
/// and the answer is normalized into stored, validated artifacts.
///
/// The order of the stream is the order the plan becomes real: one `stage` per artifact as
/// it lands, then `done` with the plan id, or `error` with the reason on the plan row. A
/// partial answer is a **failed plan carrying its artifacts** — never a `draft` with half a
/// plan and a green status, which is the one state a reviewer could mistake for a finished
/// one.
pub async fn generate(
    State(state): State<AppState>,
    current: CurrentSession,
    address: ClientAddress,
    Json(body): Json<GenerateBody>,
) -> Result<Sse<impl tokio_stream::Stream<Item = Result<Event, Infallible>>>, ApiError> {
    let organization_id = organization_of(&current, body.organization_id)?;

    let prompt = read_prompt(&body.prompt)?;
    // Resolution before the row is written and before the stream opens, so "no provider is
    // connected" is a `409` the composer can render inline.
    let resolved = resolve(state.db().pool(), body.model.as_deref())
        .await
        .map_err(provider_error)?;
    let model_id = resolved.id();

    let plan = builder::insert_plan(
        state.db().pool(),
        builder::NewPlan {
            organization_id: Some(organization_id),
            site_id: None,
            prompt: prompt.clone(),
            title: body
                .title
                .as_deref()
                .map(str::trim)
                .filter(|title| !title.is_empty())
                .map(str::to_owned),
            model_label: model_id.clone(),
            created_by: Some(current.user.id),
            supersedes_id: None,
        },
    )
    .await
    .map_err(store_error)?;

    record(
        &state,
        NewAuditEntry::by_user(current.user.id, "app_builder.plan.created")
            .organization(organization_id)
            .target("app_builder_plan", plan.id.to_string())
            .metadata(json!({ "model": model_id }))
            .ip_address(address.as_text()),
    )
    .await?;

    let (frames, receiver) = mpsc::channel::<Frame>(STREAM_BUFFER);
    let pool = state.db().pool().clone();
    let plan_id = plan.id;
    let user_id = current.user.id;
    tokio::spawn(async move {
        let mut run = GenerationRun {
            pool: pool.clone(),
            plan_id,
            user_id,
            usage: None,
        };

        let answer = match run.ask(&resolved, &prompt).await {
            Ok(answer) => answer,
            Err(failure) => {
                // Every failure ends in the same two things: the stream says why, and the
                // plan row carries the same reason so a reviewer who reloads the console
                // finds the attempt and not just an empty list.
                let _ = frames.send(Frame::Failed(failure.clone())).await;
                let _ = run.fail(failure.message).await;
                return;
            }
        };

        let generated = builder::normalize(&answer);

        // Artifacts land one at a time so the tree fills in while the reviewer watches.
        // Each is stored through the store, which derives its status from the validator's
        // answer — a generator cannot accept its own work.
        for artifact in &generated.artifacts {
            let findings = builder::validate_artifact(artifact);
            match builder::insert_artifact(&pool, plan_id, artifact, &findings).await {
                Ok(stored) => {
                    let _ = frames
                        .send(Frame::Artifact {
                            kind: stored.kind,
                            key: stored.key,
                            status: stored.status,
                            findings: findings.len(),
                        })
                        .await;
                }
                Err(error) => {
                    // A refusal by the store — a reserved key, a body that is not an object,
                    // a rationale over the limit — is reported by name and ends the run. The
                    // artifacts already written stay: they are inert drafts, and a reviewer
                    // who wants them has them.
                    let message = error.to_string();
                    let failure = Failure::new(error_code(&error), message.clone());
                    let _ = frames.send(Frame::Failed(failure)).await;
                    let _ = run.fail(message).await;
                    return;
                }
            }
        }

        if let Err(failure) = run.settle(&generated).await {
            let _ = frames.send(Frame::Failed(failure.clone())).await;
            let _ = run.fail(failure.message).await;
            return;
        }

        // Whatever the platform had to repair is on the stream and on the plan, never only
        // in this function: a plan that was quietly fixed is a plan nobody can trust.
        for note in &generated.notes {
            let _ = frames.send(Frame::Note(note.clone())).await;
        }

        let _ = frames
            .send(Frame::Done {
                plan_id,
                artifacts: generated.artifacts.len(),
                missing: builder::missing_required_kinds(&generated.artifacts),
            })
            .await;
    });

    Ok(Sse::new(ReceiverStream::new(receiver).map(Frame::event)).keep_alive(KeepAlive::default()))
}

/// The generation's writes: one plan row, one call, one settlement.
///
/// A struct because the three steps share a plan id and a pool, and three functions each
/// taking `(&PgPool, Uuid)` is three chances to pass the wrong pair — the same reason
/// `PlanStore` exists one layer down.
struct GenerationRun {
    pool: sqlx::PgPool,
    plan_id: Uuid,
    user_id: Uuid,
    /// What the one call cost, when the provider reported it. `None` stays distinct from a
    /// reported `0`, and the plan carries `null` rather than a fabricated number.
    usage: Option<omnion_ai_hub::ChatUsage>,
}

/// Why a generation stopped, in the two forms its two readers need: a stable code for the
/// stream and a sentence for the plan row.
#[derive(Clone)]
struct Failure {
    code: &'static str,
    message: String,
}

impl Failure {
    fn new(code: &'static str, message: impl Into<String>) -> Self {
        Self {
            code,
            message: message.into(),
        }
    }
}

impl GenerationRun {
    /// Ask the provider once, with the platform's schema prompt.
    ///
    /// One call, no repair round-trip: a second call would double the cost of a plan that
    /// was merely mis-cased, and every repair this platform performs is a spelling the
    /// reviewer can read in the artifact's rationale. A genuinely wrong answer is
    /// regenerated by the reviewer's own hand, artifact by artifact.
    async fn ask(
        &mut self,
        resolved: &omnion_ai_hub::ResolvedModel,
        prompt: &str,
    ) -> Result<Value, Failure> {
        let target = omnion_ai_hub::client::ProviderTarget::from_provider(&resolved.provider);
        let request = omnion_ai_hub::client::ChatRequest {
            model: resolved.model.model_key.clone(),
            messages: vec![
                omnion_ai_hub::client::ChatMessage::system(
                    "You design enterprise applications. Answer with one JSON object and \
                     nothing else: no prose, no markdown, no code fence.",
                ),
                omnion_ai_hub::client::ChatMessage::user(builder::schema_prompt(prompt)),
            ],
            // Low, because the answer is a schema: two valid answers to the same request
            // are the defect, not the freedom.
            temperature: Some(0.1),
            // Generous, because a plan is eight artifacts and a truncated answer is an
            // incomplete plan rather than a smaller one.
            max_tokens: Some(8192),
        };

        let outcome = omnion_ai_hub::client::chat(&target, &request)
            .await
            .map_err(|error| Failure::new("ai_provider_error", error.to_string()))?;

        // The same fenced-JSON parser the regeneration path uses: one answer shape, one
        // parser. A second copy would be a second set of tolerances.
        let answer = parse_artifact_answer(&outcome.content).ok_or_else(|| {
            Failure::new(
                "ai_provider_unreadable_answer",
                format!(
                    "the model did not answer with a JSON object ({}); the first words were: {}",
                    describe_answer_shape(&outcome.content),
                    first_words(&outcome.content)
                ),
            )
        })?;

        self.usage = outcome.usage;
        Ok(answer)
    }

    /// Move the plan to `draft` with the counts the answer cost.
    ///
    /// `draft`, never `approved`: the artifacts are validated, not reviewed, and the store
    /// refuses any other status a caller could set here for good reason.
    async fn settle(&self, generated: &builder::Generated) -> Result<(), Failure> {
        let usage = builder::PlanUsage {
            input: self
                .usage
                .as_ref()
                .and_then(|usage| usage.prompt_tokens)
                .and_then(|count| i32::try_from(count).ok()),
            output: self
                .usage
                .as_ref()
                .and_then(|usage| usage.completion_tokens)
                .and_then(|count| i32::try_from(count).ok()),
            cost_cents: 0,
        };
        builder::apply_answer(
            &self.pool,
            self.plan_id,
            "draft",
            usage,
            generated.title.as_deref(),
        )
        .await
        .map_err(|error| Failure::new("app_builder_answer_store_failed", error.to_string()))?
        .ok_or_else(|| {
            // `None` is the store's "this plan is no longer generating" answer: another
            // attempt answered it first. Naming that beats reporting a store failure.
            Failure::new(
                "app_builder_plan_not_generating",
                "another attempt answered this plan first",
            )
        })?;
        Ok(())
    }

    /// Record why the generation stopped, on the plan row.
    async fn fail(&self, message: String) {
        let _ = builder::apply_failure(&self.pool, self.plan_id, &message).await;
    }
}

// ---------------------------------------------------------------------------------------------
// Stream frames
// ---------------------------------------------------------------------------------------------

/// One frame of a generation, before it becomes an SSE event.
///
/// One variant per thing a reviewer's screen actually has to react to, because a single
/// generic `stage` carrying a string forces the client to parse English to learn what
/// happened. `Artifact` exists so the tree can fill in **while the stream is open** — the
/// request asks for that explicitly — and `Note` exists so a repair the platform made is
/// visible in the same place it will later be read from.
enum Frame {
    /// One artifact was stored. Carries the status the **validator** derived, not the one
    /// the generator hoped for.
    Artifact {
        /// Which kind landed.
        kind: String,
        /// Its key within the plan.
        key: String,
        /// `pending` or `invalid`, as the store decided.
        status: String,
        /// How many findings the validator reported.
        findings: usize,
    },
    /// Something the platform repaired or refused, said in a sentence.
    Note(String),
    /// Generation stopped; the plan row carries the same reason.
    Failed(Failure),
    /// The plan is a `draft` with its artifacts stored.
    Done {
        /// The plan that was written.
        plan_id: Uuid,
        /// How many artifacts landed.
        artifacts: usize,
        /// Required kinds the answer did not propose, **by name**.
        missing: Vec<String>,
    },
}

impl Frame {
    /// The SSE event a client reads. `data` on every frame rather than the event name alone:
    /// the payload is what carries the message, and a frame whose type is the whole message
    /// is a frame a debugger cannot show.
    fn event(self) -> Result<Event, Infallible> {
        let event = match self {
            Self::Artifact {
                kind,
                key,
                status,
                findings,
            } => Event::default().event("artifact").data(
                json!({
                    "kind": kind,
                    "key": key,
                    "status": status,
                    "findings": findings,
                })
                .to_string(),
            ),
            Self::Note(note) => Event::default()
                .event("note")
                .data(json!({ "note": note }).to_string()),
            Self::Failed(failure) => Event::default()
                .event("error")
                .data(json!({ "code": failure.code, "message": failure.message }).to_string()),
            Self::Done {
                plan_id,
                artifacts,
                missing,
            } => Event::default().event("done").data(
                json!({
                    "plan_id": plan_id,
                    "artifacts": artifacts,
                    "missing_required_kinds": missing,
                })
                .to_string(),
            ),
        };
        Ok(event)
    }
}

// ---------------------------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------------------------

/// Organization, for a platform account; a scoped account's own.
///
/// A platform account must **name** the tenant, because a plan belongs to one and there is no
/// "all tenants" console; a scoped account's own id is used and a name that disagrees is
/// refused rather than ignored — ignoring it would let a request say "organization B" and get
/// organization A's plans, and the response looks correct for the session that asked.
fn organization_of(current: &CurrentSession, requested: Option<Uuid>) -> Result<Uuid, ApiError> {
    match current.user.organization_id {
        Some(own) => {
            ensure_same_organization(current, requested)?;
            Ok(own)
        }
        None => requested.ok_or_else(|| {
            ApiError::bad_request(
                "organization_required",
                "this account is not attached to an organization — name one to read its plans",
            )
        }),
    }
}

/// Load a plan and refuse it when it is out of the caller's organization.
async fn plan_in_scope(
    state: &AppState,
    current: &CurrentSession,
    plan_id: Uuid,
) -> Result<builder::AppBuilderPlan, ApiError> {
    let organization_id = organization_of(current, None)?;
    builder::find_plan_in(state.db().pool(), plan_id, Some(organization_id))
        .await
        .map_err(store_error)?
        .ok_or_else(plan_not_found)
}

/// Load an artifact **through its plan**, so a path carrying another tenant's plan id and a
/// valid artifact id answers `404` rather than editing it.
async fn artifact_of_plan(
    state: &AppState,
    current: &CurrentSession,
    plan_id: Uuid,
    artifact_id: Uuid,
) -> Result<builder::AppBuilderArtifact, ApiError> {
    let artifact = builder::find_artifact(state.db().pool(), artifact_id)
        .await
        .map_err(store_error)?
        .ok_or_else(artifact_not_found)?;
    if artifact.plan_id != plan_id {
        return Err(artifact_not_found());
    }
    // The plan is loaded through the tenancy check before the artifact is read, so an
    // out-of-scope plan's artifact is never even looked at.
    plan_in_scope(state, current, plan_id).await?;
    Ok(artifact)
}

/// The `404` a missing and an out-of-scope plan both answer.
///
/// One function because the two must be indistinguishable: a handler that refused an
/// out-of-scope plan with `403` would tell the caller the id exists somewhere.
fn plan_not_found() -> ApiError {
    ApiError::new(
        StatusCode::NOT_FOUND,
        "app_builder_plan_not_found",
        "no such app builder plan",
    )
}

/// The same for an artifact.
fn artifact_not_found() -> ApiError {
    ApiError::new(
        StatusCode::NOT_FOUND,
        "app_builder_artifact_not_found",
        "no such artifact in this plan",
    )
}

/// Read and bound a prompt, with the composer's own message for each failure.
fn read_prompt(raw: &str) -> Result<String, ApiError> {
    let prompt = raw.trim();
    let length = prompt.chars().count();
    if length < builder::MIN_PROMPT_LEN {
        return Err(ApiError::bad_request(
            "prompt_too_short",
            format!(
                "describe the app in at least {} characters — a sentence the model can act on",
                builder::MIN_PROMPT_LEN
            ),
        ));
    }
    if length > builder::MAX_PROMPT_LEN {
        return Err(ApiError::bad_request(
            "prompt_too_long",
            format!(
                "a prompt is at most {} characters; this one is {length}",
                builder::MAX_PROMPT_LEN
            ),
        ));
    }
    Ok(prompt.to_owned())
}

/// The counters and blockers a decision's answer carries.
async fn decision_body(
    state: &AppState,
    plan: &builder::AppBuilderPlan,
    artifact: builder::AppBuilderArtifact,
) -> Result<Json<ArtifactDecisionBody>, ApiError> {
    let counts = builder::artifact_counts(state.db().pool(), plan.id)
        .await
        .map_err(store_error)?;
    let blockers = builder::blockers(state.db().pool(), plan.id)
        .await
        .map_err(store_error)?;

    Ok(Json(ArtifactDecisionBody {
        artifact: ArtifactBody::build(&artifact),
        counts,
        blockers: blockers.iter().map(BlockedBody::from).collect(),
    }))
}

/// One generation's answer, reduced to what an artifact rewrite needs.
struct Regeneration {
    /// The artifact body the model returned.
    artifact: Value,
    /// Its own explanation.
    rationale: String,
    /// The model that answered.
    model_label: String,
    /// What it cost, in tokens.
    tokens: i64,
}

/// Ask a model for one artifact's body.
///
/// Slice 3's job in full is the typed plan generator with the platform's artifact schema; what
/// a **single-artifact regeneration** needs is much smaller and is implemented here, because
/// the request asks for "regenerate one artifact with feedback" as a review-screen action and
/// leaving it out would leave the button with nothing behind it.
///
/// **The AI Hub client is used directly rather than `omnion_module_ai::generate`**, and that
/// is not a shortcut — the two answer different questions. The workflow builder's generator
/// asks for a *definition* in a closed shape its own validator owns (a trigger and a list of
/// steps), so its answer has fields this module has no use for; borrowing it would mean
/// validating one artifact through a rule written for a whole workflow. What this needs is one
/// provider call and one parse.
///
/// The answer is read as **an object** and nothing else is accepted, and the reason is the
/// module's premise: model output is untrusted input. Prose, a fenced code block or an array is
/// refused here with the model's own words in the message, rather than stored as a `spec` the
/// validator would later describe as "not an object" — the reviewer sees the refusal next to
/// the button they pressed instead of after a reload.
async fn run_generation(
    resolved: &omnion_ai_hub::ResolvedModel,
    prompt: &str,
) -> Result<Regeneration, ApiError> {
    let target = omnion_ai_hub::client::ProviderTarget::from_provider(&resolved.provider);
    let request = omnion_ai_hub::client::ChatRequest {
        model: resolved.model.model_key.clone(),
        messages: vec![
            omnion_ai_hub::client::ChatMessage::system(
                "You revise one artifact of an application plan. Answer with a single JSON \
                 object and nothing else — no prose, no code fence. The object carries the \
                 artifact's own fields, plus an optional `rationale` string explaining what \
                 changed.",
            ),
            omnion_ai_hub::client::ChatMessage::user(prompt.to_owned()),
        ],
        temperature: Some(0.2),
        max_tokens: Some(4096),
    };

    let outcome = omnion_ai_hub::client::chat(&target, &request)
        .await
        .map_err(|error| {
            ApiError::new(
                StatusCode::BAD_GATEWAY,
                "ai_provider_error",
                error.to_string(),
            )
        })?;

    let tokens = outcome
        .usage
        .as_ref()
        .and_then(|usage| usage.total_tokens)
        .and_then(|count| i64::try_from(count).ok())
        .unwrap_or_default();

    let body = parse_artifact_answer(&outcome.content).ok_or_else(|| {
        ApiError::new(
            StatusCode::BAD_GATEWAY,
            "ai_provider_unreadable_answer",
            format!(
                "the model did not answer with a JSON object ({}); the first words were: {}",
                describe_answer_shape(&outcome.content),
                first_words(&outcome.content)
            ),
        )
    })?;

    // `rationale` is the model's own explanation, kept beside the artifact so the reviewer
    // can see what changed rather than only what changed. A body without one is not refused
    // here — the validator records "no rationale" as a finding beside it, which is the
    // module's own way of saying the same thing without throwing the artifact away.
    let rationale = body
        .get("rationale")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_owned();
    let artifact = body
        .get("artifact")
        .cloned()
        .unwrap_or_else(|| body.clone());

    Ok(Regeneration {
        artifact,
        rationale,
        model_label: resolved.id(),
        tokens,
    })
}

/// Parse a model's answer as JSON, tolerating a fenced code block.
///
/// The fence tolerance is narrow and deliberate: a model that wraps its JSON in ```` ```json ````
/// is overwhelmingly still answering the question, and refusing it would send the reviewer to
/// press Regenerate again and pay twice for the same artifact. Anything that is not an object
/// after the fence is stripped is refused — this is not a "find the first `{` anywhere in the
/// text" parser, because that happily reads the first brace of a sentence as an artifact.
fn parse_artifact_answer(content: &str) -> Option<Value> {
    let trimmed = content.trim();
    let body = match trimmed.strip_prefix("```") {
        Some(rest) => rest
            .strip_prefix("json")
            .or_else(|| rest.strip_prefix("JSON"))
            .map_or(rest, str::trim)
            .trim_end_matches("```")
            .trim(),
        None => trimmed,
    };
    serde_json::from_str::<Value>(body)
        .ok()
        .filter(Value::is_object)
}

/// Name what the answer turned out to be, for the refusal message.
fn describe_answer_shape(content: &str) -> &'static str {
    match serde_json::from_str::<Value>(content.trim()) {
        Ok(Value::Array(_)) => "an array",
        Ok(Value::String(_)) => "a bare string",
        Ok(Value::Null) => "null",
        Ok(_) => "not a JSON object",
        Err(_) => "not JSON at all",
    }
}

/// The first few words of an unreadable answer, so the message is diagnosable.
fn first_words(content: &str) -> String {
    let words: Vec<&str> = content.split_whitespace().take(8).collect();
    let joined = words.join(" ");
    if joined.chars().count() > 120 {
        format!("{}…", joined.chars().take(120).collect::<String>())
    } else {
        joined
    }
}

impl From<&builder::BlockedArtifact> for BlockedBody {
    fn from(artifact: &builder::BlockedArtifact) -> Self {
        Self {
            kind: artifact.kind.clone(),
            key: artifact.key.clone(),
            status: artifact.status.clone(),
            reason: artifact.reason.clone(),
        }
    }
}

/// Turn a store failure into a `500` with the module's own code.
/// The store's stable code for a refusal, so a stream `error` frame carries the same code
/// the HTTP layer would have answered.
///
/// A database failure has no plan-shaped code, so it gets its own: a stream that reported
/// `invalid_artifact_key` for a dropped connection would send the reviewer to fix their
/// model prompt instead of retrying.
fn error_code(error: &builder::AppBuilderError) -> &'static str {
    match error {
        builder::AppBuilderError::Invalid { code, .. } => code,
        builder::AppBuilderError::Ai(_) => "ai_provider_error",
        builder::AppBuilderError::Blocked(_) => "apply_blocked",
        _ => "app_builder_store_error",
    }
}

fn store_error(error: builder::AppBuilderError) -> ApiError {
    ApiError::new(
        StatusCode::INTERNAL_SERVER_ERROR,
        error.code(),
        error.to_string(),
    )
}

/// Turn a rule refusal into the status the review screen renders.
///
/// `422` with the module's stable code and message, which is what the request's API table
/// asks for ("edits that break a key return `422` with the field path") and what the artifact
/// pane shows as the finding beside the editor.
fn validation_error(error: builder::AppBuilderError) -> ApiError {
    match error {
        builder::AppBuilderError::Invalid { code, message } => {
            ApiError::new(StatusCode::UNPROCESSABLE_ENTITY, code, message)
        }
        other => store_error(other),
    }
}

/// Turn a routing failure into the status the composer's states are written for.
///
/// `409` rather than `503`: nothing is wrong with the platform, the installation has no model
/// this request could use, and the console's remedy is a link to `/ai` — which is what "no
/// provider connected" *is* in the spec.
fn provider_error(error: omnion_ai_hub::AiHubError) -> ApiError {
    let (status, code) = match error {
        omnion_ai_hub::AiHubError::ProviderNotFound
        | omnion_ai_hub::AiHubError::ModelNotFound
        | omnion_ai_hub::AiHubError::NoDefaultModel
        | omnion_ai_hub::AiHubError::ProviderDisabled(_) => {
            (StatusCode::CONFLICT, "ai_no_model_available")
        }
        _ => (StatusCode::BAD_GATEWAY, "ai_provider_error"),
    };
    ApiError::new(status, code, error.to_string())
}

/// Write an audit row, and let its failure be a `500` like any other write's.
async fn record(state: &AppState, entry: NewAuditEntry) -> Result<(), ApiError> {
    omnion_audit::record(state.db().pool(), entry).await?;
    Ok(())
}
