/**
 * Shared types of the Omnion platform.
 *
 * The API (`apps/api`) is the source of truth for every shape here; this package is the
 * TypeScript mirror the apps and themes import instead of restating the JSON by hand. It is
 * types-only on purpose — nothing in here reaches a bundle.
 */

/**
 * Site a piece of public content belongs to.
 *
 * The public surface answers with the site's handle, display name and the theme it renders
 * with: internal identifiers stay inside the panel (docs/05-VERSIONING.md §6).
 */
export interface PublicSite {
  /** Stable handle of the site inside its organization (`main`). */
  key: string;
  /** Display name of the site. */
  name: string;
  /** Theme the renderer activates (`themes/<key>`); unknown keys fall back to the default. */
  theme: string;
}

/** Public identity of a page. */
export interface PublicPage {
  /** Address of the page inside its site (`about-us`). */
  slug: string;
  /** Content type key (`page` today; the content type builder extends the set). */
  page_type: string;
  /** Last change, RFC 3339. */
  updated_at: string;
}

/** The published revision of a page — what a visitor actually reads. */
export interface PublicRevision {
  /** Monotonic revision number inside the page. */
  revision_no: number;
  /** Title. */
  title: string;
  /** Body. A page whose `blocks` tree is empty renders from this, so a revision written
   *  before the block system keeps rendering exactly as it did. */
  body: string;
  /** Summary, when the author wrote one. */
  summary: string | null;
  /** The block tree the theme renders (REQ-063). `[]` renders the body instead. */
  blocks: unknown[];
  /** When the revision was published, RFC 3339 — `null` while it never was. */
  published_at: string | null;
}

/**
 * One block of a page (REQ-063).
 *
 * Ids are client-generated and stable across reorders, which is what lets a revision diff
 * read as a move rather than a rewrite. A leaf block carries no `children` key at all.
 */
export interface ContentBlock {
  /** Stable id, generated by the editor. */
  id: string;
  /** Block type key — one of the registry's types. */
  type: string;
  /** The type's props, shaped by the registry's schema. */
  props: Record<string, unknown>;
  /**
   * Per-block settings — `hide_on`, `align`, `anchor`, `id`, `class`, `aria_label`.
   *
   * Separate from `props` because a prop is content the block's schema declares and a setting is
   * how the author placed this block. A block with nothing set carries no `meta` key at all, so
   * the ordinary block costs nothing in the stored payload.
   */
  meta?: BlockSettings;
  /** Child blocks, for container types only. */
  children?: ContentBlock[];
}

/** The viewports a block can be hidden from. */
export type HideOn = "none" | "mobile" | "desktop";

/** The viewports `HideOn` allows, in the order the inspector lists them. */
export const HIDE_ON_VALUES: HideOn[] = ["none", "mobile", "desktop"];

/** The per-block settings the platform reads. */
export interface BlockSettings {
  /** Viewport the block is hidden from. `none` — or no `meta` at all — shows it everywhere. */
  hide_on?: HideOn;
  /** Text alignment the block asks for. */
  align?: string;
  /** Anchor the renderer puts on the block, for a `#link` to reach it. */
  anchor?: string;
  /** DOM id, for a `#link` to reach the block directly. */
  id?: string;
  /** Extra class names the theme's stylesheet may key on. */
  class?: string;
  /** Accessible name for a block whose content is not its label. */
  aria_label?: string;
}

/** What kind of value one block prop holds. */
export type BlockPropType = "string" | "text" | "number" | "boolean" | "enum" | "list";

/** One field of a block type, as the registry describes it. */
export interface BlockPropSchema {
  /** Field name inside `props`. */
  key: string;
  /** Label the inspector shows. */
  label: string;
  /** Value kind. */
  type: BlockPropType;
  /** `true` when the block cannot be published without it. */
  required: boolean;
  /** Allowed values, for `enum` props. */
  enum?: string[];
  /** Longest accepted value, in characters. */
  maxLength?: number;
  /** Value a freshly inserted block starts with. */
  default: unknown;
}

/** One block type the platform ships. */
export interface BlockDefinition {
  /** Stable key stored in the payload. */
  key: string;
  /** Label the insert panel lists it as. */
  label: string;
  /** Grouping in the insert panel and the registry reference. */
  category: string;
  /** One line describing what the block is for. */
  description: string;
  /** `true` when the block holds child blocks. */
  container: boolean;
  /**
   * `true` when the block exists only as another block's child and the insert panel must not
   * offer it — `column` is one. It is still registered, validated, rendered and diffed.
   */
  structure_only: boolean;
  /** HTML element the renderer emits. */
  semantic: string;
  /** `true` when the block can be hidden per viewport. */
  viewport_aware: boolean;
  /** Its fields, in inspector order. */
  props: BlockPropSchema[];
}

/**
 * The bounds the server enforces on a block tree, as the registry publishes them.
 *
 * These were hand-mirrored in `block-tree.ts` with a comment on each saying "mirrors the
 * server's" — and nothing anywhere that compared the two, so a bound that moved on one side
 * produced an editor that allowed what the API refused (or the reverse) until an author hit it.
 * They travel with the registry so the panel is told the number instead of keeping its own.
 */
export interface BlockLimits {
  /** Deepest nesting a tree may reach. */
  max_depth: number;
  /** Most blocks one page's draft may carry, nested included. */
  max_blocks: number;
  /** Largest a serialized tree may be. */
  max_blocks_bytes: number;
  /** Fewest columns a Columns block holds. */
  min_columns: number;
  /** Most columns a Columns block holds. */
  max_columns: number;
}

/** The registry document (`GET /api/v1/blocks`). */
export interface BlockRegistry {
  /** Registry version, for the panel and the renderer to compare against. */
  version: string;
  /** Category order the insert panel groups by. */
  categories: string[];
  /** The bounds the validator enforces, so the editor enforces the same ones. */
  limits: BlockLimits;
  /** Every block type the platform ships. */
  blocks: BlockDefinition[];
}

/** One thing wrong with one block. */
export interface BlockIssue {
  /** Block the issue belongs to. */
  block_id: string;
  /** Block type, when the type itself could not be read. */
  block_type?: string;
  /** Dotted path to the offending value (`[0].props.alt`). */
  path: string;
  /** Stable machine-readable code. */
  code: string;
  /** What the author should do about it. */
  message: string;
  /** `error` blocks a publish; `warning` does not. */
  severity: "error" | "warning";
}

/** The answer of the dry run (`POST /api/v1/blocks/validate`). */
export interface BlockValidationResult {
  /** The issues, errors first. */
  issues: BlockIssue[];
  /** Blocks counted, nested included. */
  block_count: number;
  /** `true` when no error blocks the publish. */
  can_publish: boolean;
}

// -- Patterns and page templates (REQ-063, slice 3) -----------------------------------------------------

/** One reusable block group in the pattern library. */
export interface ContentPattern {
  /** Pattern id. */
  id: string;
  /** Organization the pattern belongs to. */
  organization_id: string;
  /** Stable key, unique inside the organization. */
  key: string;
  /** Name the card shows. */
  name: string;
  /** Grouping the library filters by. */
  category: string;
  /** One line describing the group. */
  description: string | null;
  /** Blocks in the group, nested included. */
  block_count: number;
  /** The block group itself. */
  blocks: ContentBlock[];
  /** Last change, ISO 8601. */
  updated_at: string;
}

/** One page template in the gallery. */
export interface PageTemplateSummary {
  /** Template id. */
  id: string;
  /** Stable key. */
  key: string;
  /** Name the card shows. */
  name: string;
  /** Content type a page created from it gets. */
  page_type: string;
  /** One line describing it. */
  description: string | null;
  /** Blocks in the template, nested included. */
  block_count: number;
  /** `true` when the platform ships this template and it cannot be deleted. */
  is_system: boolean;
  /** The page's blocks, for the gallery's preview. */
  blocks: ContentBlock[];
}

/** Response of `GET /api/v1/patterns`. */
export interface PatternListResponse {
  /** Organization the patterns belong to. */
  organization_id: string;
  /** Patterns, newest first. */
  patterns: ContentPattern[];
}

/** Response of `GET /api/v1/page-templates`. */
export interface TemplateListResponse {
  /** Templates, gallery order. */
  templates: PageTemplateSummary[];
}

/** Response of `GET /api/v1/patterns/{id}/blocks` — the blocks a page will store. */
export interface PatternBlocksResponse {
  /** The pattern the blocks came from. */
  pattern_id: string;
  /** The blocks, with ids minted fresh for the page they are going into. */
  blocks: ContentBlock[];
  /** Blocks in the pattern, nested included. */
  block_count: number;
}

/**
 * A page's featured image, ready for a theme to draw (REQ-064 slice 4d).
 *
 * `null` is the answer for BOTH "this page has no image" and "this page's image is in the
 * trash" — a renderer's only decision is whether to emit an `<img>`, and the two cases answer it
 * identically. The *panel* is where the difference shows, because there the operator has something
 * to do about one and nothing to do about the other.
 */
export interface PublicFeaturedImage {
  /** Media id, for the DOM and for a "open the file" link. */
  media_id: string;
  /** The URL the API serves the object at. Never build this by hand in a theme. */
  url: string;
  /** Alt text. Guaranteed non-blank by the store and by the schema. */
  alt: string;
  /** Caption to draw under the image; possibly empty. */
  legend: string;
  /**
   * The focal point as a CSS `object-position`, or `null` when the page has never been cropped.
   *
   * A string rather than two numbers because every consumer writes it into CSS, and handing them
   * `Some((0.5, 0.5))` is handing them the question of how to format it.
   */
  object_position: string | null;
  /** Pixel width, or `null` when the format carries none. */
  width: number | null;
  /** Pixel height. */
  height: number | null;
}

/** Response of `GET /api/v1/public/pages/{slug}` — one renderable page. */
export interface PublishedPage {
  /** Site the page belongs to. */
  site: PublicSite;
  /** The page itself. */
  page: PublicPage;
  /** The revision visitors see. */
  revision: PublicRevision;
  /**
   * The page's featured image, or `null` when there is nothing to draw.
   *
   * On THIS response rather than behind a second request on purpose: a renderer that has to ask
   * whether a page has a picture is a renderer that can render a page without one.
   */
  featured_image: PublicFeaturedImage | null;
}
